services:
  governanceplatform:
    container_name: governanceplatform
    image: ${NISINP_IMAGE:-ghcr.io/informed-governance-project/nisinp}:${NISINP_VERSION?:err}
    pull_policy: always
    network_mode: host
    volumes:
      - ./volumes/config/config.py:/app/governanceplatform/config.py:ro
      # the three below need to be writable by www-data (uid 33)
      - ./volumes/default-theme:/app/theme
      - ./volumes/static:/app/governanceplatform/static
      - ./volumes/logs:/app/governanceplatform/logs
    restart: unless-stopped
