services:
  web:
    container_name: governanceplatform-${NISINP_ENVIRONMENT?:err}
    image: ${NISINP_IMAGE:-ghcr.io/informed-governance-project/nisinp}:${NISINP_VERSION?:err}
    pull_policy: always
    environment: &env
      DEBUG: "false"
      POSTGRES_USER: "<user>"
      POSTGRES_PASSWORD: "<password>"
      POSTGRES_DB: "serima-governance"
      POSTGRES_HOST: "postgres"
    ports:
      - "8888:8888"
    volumes:
      - ./volumes/config/config.py:/app/governanceplatform/config.py:ro
      # the below volumes need to be writable by www-data (uid 33)
      - ./volumes/default-theme:/app/theme
    restart: unless-stopped
  postgres:
    container_name: governanceplatform-postgres-${NISINP_ENVIRONMENT?:err}
    image: postgres:15
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
      # enable the below volume if you want to load a pg_dump at init
      #- ./volumes/postgres/initdb.d:/docker-entrypoint-initdb.d
    environment: *env
    restart: unless-stopped
