# Generated by Django 4.2.15 on 2024-08-13 10:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import parler.fields
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("governanceplatform", "0020_alter_regulator_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Asset name")),
                (
                    "asset_type_uuid",
                    models.CharField(max_length=32, verbose_name="Asset Type uuid"),
                ),
            ],
            options={
                "verbose_name": "Assets",
                "verbose_name_plural": "Asset",
            },
        ),
        migrations.CreateModel(
            name="RecommendationData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Recommendation name"
                    ),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Recommendation description"),
                ),
            ],
            options={
                "verbose_name": "Recommendation",
                "verbose_name_plural": "Recommendations",
            },
        ),
        migrations.CreateModel(
            name="RiskAnalysisJson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField(verbose_name="Data")),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Timestamp"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="governanceplatform.company",
                        verbose_name="Company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScaleData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("minimum", models.IntegerField(verbose_name="Minimum")),
                ("maximum", models.IntegerField(verbose_name="Maximum")),
                (
                    "risk_analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reporting.riskanalysisjson",
                        verbose_name="Risk Analysis",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ThreatData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.CharField(max_length=32, verbose_name="uuid")),
            ],
            options={
                "verbose_name": "Threat",
                "verbose_name_plural": "Threats",
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="VulnerabilityData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.CharField(max_length=32, verbose_name="uuid")),
            ],
            options={
                "verbose_name": "Vulnerability",
                "verbose_name_plural": "Vulnerabilities",
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ServiceStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_name",
                    models.CharField(max_length=255, verbose_name="Service name"),
                ),
                (
                    "treshold_for_high_risk",
                    models.FloatField(verbose_name="High risk rate treshold"),
                ),
                ("high_risk_rate", models.FloatField(verbose_name="High risk rate")),
                (
                    "high_risk_average",
                    models.FloatField(verbose_name="Average high risk"),
                ),
                (
                    "risk_analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reporting.riskanalysisjson",
                        verbose_name="Risk Analysis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Risk analysis stat",
                "verbose_name_plural": "Risk analysis stats",
            },
        ),
        migrations.CreateModel(
            name="SectorStatistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Timestamp"
                    ),
                ),
                (
                    "high_risk_average",
                    models.FloatField(verbose_name="Average high risk"),
                ),
                ("risk_average", models.FloatField(verbose_name="High risk")),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="governanceplatform.sector",
                        verbose_name="Sector",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sector stat",
                "verbose_name_plural": "Secrtor stats",
            },
        ),
        migrations.CreateModel(
            name="RiskData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("threat_value", models.FloatField(verbose_name="Threat value")),
                (
                    "vulnerability_value",
                    models.FloatField(verbose_name="Vulnerability value"),
                ),
                (
                    "risk_level_value",
                    models.FloatField(verbose_name="Risk level value"),
                ),
                (
                    "residual_risk_level_value",
                    models.FloatField(verbose_name="Residual risk level value"),
                ),
                (
                    "risk_treatment",
                    models.CharField(
                        choices=[
                            ("REDUC", "Reduction"),
                            ("DENIE", "Deny"),
                            ("ACCEP", "Acceptation"),
                            ("SHARE", "Shared"),
                            ("UNTRE", "Untreated"),
                        ],
                        default="DENIE",
                        max_length=5,
                        verbose_name="Risk treatment",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reporting.servicestat",
                        verbose_name="Service",
                    ),
                ),
                (
                    "threat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reporting.threatdata",
                        verbose_name="Threat",
                    ),
                ),
                (
                    "vulnerability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reporting.vulnerabilitydata",
                        verbose_name="Vulnerability",
                    ),
                ),
            ],
            options={
                "verbose_name": "Risk",
                "verbose_name_plural": "Risks",
            },
        ),
        migrations.CreateModel(
            name="AssetScale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField(verbose_name="Value")),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reporting.assetdata",
                        verbose_name="Asset",
                    ),
                ),
                (
                    "scale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reporting.scaledata",
                        verbose_name="Scale",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="assetdata",
            name="impacts",
            field=models.ManyToManyField(
                through="reporting.AssetScale",
                to="reporting.scaledata",
                verbose_name="Scales value",
            ),
        ),
        migrations.CreateModel(
            name="VulnerabilityDataTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=255,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="reporting.vulnerabilitydata",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vulnerability Translation",
                "db_table": "reporting_vulnerabilitydata_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ThreatDataTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=255,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="reporting.threatdata",
                    ),
                ),
            ],
            options={
                "verbose_name": "Threat Translation",
                "db_table": "reporting_threatdata_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ScaleDataTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=255,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="reporting.scaledata",
                    ),
                ),
            ],
            options={
                "verbose_name": "scale data Translation",
                "db_table": "reporting_scaledata_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
