# Generated by Django 5.1 on 2024-08-21 09:12

import uuid

import django.db.models.deletion
import django.utils.timezone
import parler.fields
import parler.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("governanceplatform", "0020_alter_regulator_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="uuid"
                    ),
                ),
            ],
            options={
                "verbose_name": "Assets",
                "verbose_name_plural": "Asset",
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Observation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Observation",
                "verbose_name_plural": "Observations",
            },
        ),
        migrations.CreateModel(
            name="ObservationRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=255, verbose_name="Recommendation name"
                    ),
                ),
            ],
            options={
                "verbose_name": "Recommendation for observation",
                "verbose_name_plural": "Recommendations for observation",
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="RecommendationData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=255, verbose_name="Recommendation name"
                    ),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Recommendation description"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="uuid"
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        default=False, verbose_name="Status of the recommendation"
                    ),
                ),
                ("due_date", models.DateTimeField(verbose_name="Due date")),
            ],
            options={
                "verbose_name": "Recommendation",
                "verbose_name_plural": "Recommendations",
            },
        ),
        migrations.CreateModel(
            name="ThreatData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="uuid"
                    ),
                ),
            ],
            options={
                "verbose_name": "Threat",
                "verbose_name_plural": "Threats",
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="VulnerabilityData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="uuid"
                    ),
                ),
            ],
            options={
                "verbose_name": "Vulnerability",
                "verbose_name_plural": "Vulnerabilities",
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ObservationRecommendationSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "introduction_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Introduction date",
                    ),
                ),
                (
                    "Observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reporting.observation",
                        verbose_name="Observation",
                    ),
                ),
                (
                    "ObservationRecommendation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reporting.observationrecommendation",
                        verbose_name="Recommendation for observation",
                    ),
                ),
                (
                    "introducer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Introducer",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="observation",
            name="observation_recommendations",
            field=models.ManyToManyField(
                through="reporting.ObservationRecommendationSelection",
                to="reporting.observationrecommendation",
                verbose_name="Observation recommendations",
            ),
        ),
        migrations.CreateModel(
            name="ReportConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "threshold_for_high_risk",
                    models.FloatField(verbose_name="High risk rate threshold"),
                ),
                (
                    "number_of_year_considered",
                    models.PositiveSmallIntegerField(
                        verbose_name="Number of year considered"
                    ),
                ),
                (
                    "high_risk_number_for_top",
                    models.PositiveSmallIntegerField(
                        verbose_name="Number of high risks for top"
                    ),
                ),
                (
                    "threat_number_for_top",
                    models.PositiveSmallIntegerField(
                        verbose_name="Number of threats for top"
                    ),
                ),
                (
                    "vulnerability_number_for_top",
                    models.PositiveSmallIntegerField(
                        verbose_name="Number of vulnerabilities for top"
                    ),
                ),
                (
                    "asset_number_for_top",
                    models.PositiveSmallIntegerField(
                        verbose_name="Number of assets for top"
                    ),
                ),
                (
                    "asset_recommendation_for_top",
                    models.PositiveSmallIntegerField(
                        verbose_name="Number of recommendations for top"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="governanceplatform.company",
                        verbose_name="Company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration",
                "verbose_name_plural": "Configurations",
            },
        ),
        migrations.CreateModel(
            name="RiskAnalysisJson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField(verbose_name="Data")),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Timestamp"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="governanceplatform.company",
                        verbose_name="Company",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="observation",
            name="risk_analysis",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="reporting.riskanalysisjson",
                verbose_name="Risk Analysis",
            ),
        ),
        migrations.CreateModel(
            name="SectorStatistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Timestamp"
                    ),
                ),
                (
                    "high_risk_average",
                    models.FloatField(verbose_name="Average high risk"),
                ),
                ("risk_average", models.FloatField(verbose_name="High risk")),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="governanceplatform.sector",
                        verbose_name="Sector",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sector stat",
                "verbose_name_plural": "Sector stats",
            },
        ),
        migrations.CreateModel(
            name="ServiceStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "threshold_for_high_risk",
                    models.FloatField(verbose_name="High risk rate threshold"),
                ),
                ("high_risk_rate", models.FloatField(verbose_name="High risk rate")),
                (
                    "high_risk_average",
                    models.FloatField(verbose_name="Average high risk"),
                ),
                (
                    "risk_analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reporting.riskanalysisjson",
                        verbose_name="Risk Analysis",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reporting.assetdata",
                        verbose_name="Asset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Risk analysis stat",
                "verbose_name_plural": "Risk analysis stats",
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="RiskData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="uuid"
                    ),
                ),
                ("threat_value", models.FloatField(verbose_name="Threat value")),
                (
                    "vulnerability_value",
                    models.FloatField(verbose_name="Vulnerability value"),
                ),
                (
                    "residual_risk_level_value",
                    models.FloatField(
                        default=-1, verbose_name="Residual risk level value"
                    ),
                ),
                (
                    "risk_treatment",
                    models.CharField(
                        choices=[
                            ("REDUC", "Reduction"),
                            ("DENIE", "Deny"),
                            ("ACCEP", "Acceptation"),
                            ("SHARE", "Shared"),
                            ("UNTRE", "Untreated"),
                        ],
                        default="DENIE",
                        max_length=5,
                        verbose_name="Risk treatment",
                    ),
                ),
                (
                    "max_risk",
                    models.FloatField(default=-1, verbose_name="Maximum risk"),
                ),
                (
                    "risk_c",
                    models.FloatField(default=-1, verbose_name="Confidentility risk"),
                ),
                (
                    "risk_i",
                    models.FloatField(default=-1, verbose_name="Integrity risk"),
                ),
                (
                    "risk_a",
                    models.FloatField(default=-1, verbose_name="Availability risk"),
                ),
                (
                    "impact_c",
                    models.FloatField(default=-1, verbose_name="Confidentility impact"),
                ),
                (
                    "impact_i",
                    models.FloatField(default=-1, verbose_name="Integrity impact"),
                ),
                (
                    "impact_a",
                    models.FloatField(default=-1, verbose_name="Availability impact"),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reporting.assetdata",
                        verbose_name="Asset",
                    ),
                ),
                (
                    "recommendations",
                    models.ManyToManyField(
                        to="reporting.recommendationdata",
                        verbose_name="recommendations",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reporting.servicestat",
                        verbose_name="Service",
                    ),
                ),
                (
                    "threat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reporting.threatdata",
                        verbose_name="Threat",
                    ),
                ),
                (
                    "vulnerability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reporting.vulnerabilitydata",
                        verbose_name="Vulnerability",
                    ),
                ),
            ],
            options={
                "verbose_name": "Risk",
                "verbose_name_plural": "Risks",
            },
        ),
        migrations.CreateModel(
            name="AssetDataTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=255,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="reporting.assetdata",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assets Translation",
                "db_table": "reporting_assetdata_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ObservationRecommendationTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default=None, null=True, verbose_name="description"
                    ),
                ),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="reporting.observationrecommendation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recommendation for observation Translation",
                "db_table": "reporting_observationrecommendation_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ThreatDataTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=255,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="reporting.threatdata",
                    ),
                ),
            ],
            options={
                "verbose_name": "Threat Translation",
                "db_table": "reporting_threatdata_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="VulnerabilityDataTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=255,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="reporting.vulnerabilitydata",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vulnerability Translation",
                "db_table": "reporting_vulnerabilitydata_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
