# Generated by Django 5.1.2 on 2024-12-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reporting", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sectorreportconfiguration",
            name="number_of_year",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3")],
                verbose_name="Number of year to compare",
            ),
        ),
    ]
