# Generated by Django 5.1 on 2024-08-21 12:24

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reporting", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riskdata",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, verbose_name="uuid"),
        ),
    ]
