# Generated by Django 5.1.3 on 2024-12-06 06:38

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "governanceplatform",
            "0036_alter_functionality_type_delete_sectorcompanycontact",
        ),
        ("reporting", "0002_alter_sectorreportconfiguration_number_of_year"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="observationrecommendation",
            name="is_generic",
        ),
        migrations.AddField(
            model_name="companyreporting",
            name="sectors",
            field=models.ManyToManyField(
                to="governanceplatform.sector", verbose_name="Sectors"
            ),
        ),
        migrations.AlterField(
            model_name="observationrecommendation",
            name="sectors",
            field=models.ManyToManyField(
                to="governanceplatform.sector", verbose_name="Sectors"
            ),
        ),
        migrations.CreateModel(
            name="CompanyReportingTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, default=None, null=True, verbose_name="comment"
                    ),
                ),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="reporting.companyreporting",
                    ),
                ),
            ],
            options={
                "verbose_name": "company reporting Translation",
                "db_table": "reporting_companyreporting_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
