# Generated by Django 5.1 on 2024-08-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reporting", "0002_alter_riskdata_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recommendationdata",
            name="due_date",
            field=models.DateTimeField(null=True, verbose_name="Due date"),
        ),
    ]
