# Generated by Django 5.1.2 on 2024-12-12 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "governanceplatform",
            "0036_alter_functionality_type_delete_sectorcompanycontact",
        ),
        ("reporting", "0003_remove_observationrecommendation_is_generic_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companyreporting",
            name="sectors",
        ),
        migrations.AddField(
            model_name="companyreporting",
            name="sector",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="governanceplatform.sector",
                verbose_name="Sector",
            ),
            preserve_default=False,
        ),
    ]
