# Generated by Django 5.2 on 2025-04-29 10:35

import django.db.models.deletion
from django.db import migrations, models


def migrate_observation_recommendations(apps, schema_editor):
    Observation = apps.get_model("reporting", "Observation")
    ThroughModel = apps.get_model("reporting", "ObservationRecommendationThrough")

    for observation in Observation.objects.all():
        recommendations = observation.observation_recommendations.all()
        for index, recommendation in enumerate(recommendations):
            ThroughModel.objects.create(
                observation=observation,
                observation_recommendation=recommendation,
                order=index,
            )


class Migration(migrations.Migration):
    dependencies = [
        ("reporting", "0003_generatedreport"),
    ]

    operations = [
        migrations.CreateModel(
            name="ObservationRecommendationThrough",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reporting.observation",
                    ),
                ),
                (
                    "observation_recommendation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reporting.observationrecommendation",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("observation", "observation_recommendation")},
                "verbose_name": "Observation order",
                "verbose_name_plural": "Observations order",
            },
        ),
        migrations.RunPython(migrate_observation_recommendations),
    ]
