# Generated by Django 5.1 on 2024-08-21 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reporting", "0003_observation_observationrecommendation_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="riskdata",
            name="risk_level_value",
        ),
        migrations.AlterField(
            model_name="riskdata",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="reporting.assetdata",
                verbose_name="Asset",
            ),
        ),
        migrations.AlterField(
            model_name="riskdata",
            name="max_risk",
            field=models.FloatField(default=-1, verbose_name="Maximum risk"),
        ),
        migrations.AlterField(
            model_name="riskdata",
            name="residual_risk_level_value",
            field=models.FloatField(
                default=-1, verbose_name="Residual risk level value"
            ),
        ),
    ]
