# Generated by Django 5.1.2 on 2024-12-12 08:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "governanceplatform",
            "0036_alter_functionality_type_delete_sectorcompanycontact",
        ),
        ("reporting", "0004_remove_companyreporting_sectors_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="companyreporting",
            unique_together={("company", "sector", "year")},
        ),
        migrations.DeleteModel(
            name="CompanyReportingTranslation",
        ),
    ]
