# Generated by Django 5.1 on 2024-08-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reporting", "0004_remove_servicestat_high_risk_average_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicestat",
            name="avg_high_risk",
            field=models.FloatField(default=0, verbose_name="Average of high risks"),
        ),
        migrations.AddField(
            model_name="servicestat",
            name="high_risk_rate",
            field=models.FloatField(default=0, verbose_name="High risk rate"),
        ),
    ]
