# Generated by Django 5.2 on 2025-04-29 10:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reporting", "0004_observationrecommendationthrough"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="observation",
            name="observation_recommendations",
        ),
    ]
