# Generated by Django 5.1.2 on 2024-12-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reporting", "0005_alter_companyreporting_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyreporting",
            name="comment",
            field=models.TextField(
                blank=True, default=None, null=True, verbose_name="Comment"
            ),
        ),
    ]
