# Generated by Django 5.2 on 2025-04-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reporting", "0005_remove_observation_observation_recommendations"),
    ]

    operations = [
        migrations.AddField(
            model_name="observation",
            name="observation_recommendations",
            field=models.ManyToManyField(
                through="reporting.ObservationRecommendationThrough",
                to="reporting.observationrecommendation",
                verbose_name="Observation recommendations",
            ),
        ),
    ]
