# Generated by Django 5.1.2 on 2024-11-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0006_remove_servicestat_avg_high_risk_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="observationrecommendation",
            name="is_generic",
            field=models.BooleanField(default=False, verbose_name="Is Generic ?"),
        ),
    ]
