# Generated by Django 5.1.2 on 2024-12-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reporting", "0006_companyreporting_comment"),
        ("securityobjectives", "0002_securityobjectivesinstandard_priority"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sectorreportconfiguration",
            name="reporting_year",
        ),
        migrations.AddField(
            model_name="sectorreportconfiguration",
            name="so_excluded",
            field=models.ManyToManyField(
                to="securityobjectives.securityobjective",
                verbose_name="Security objectives excluded",
            ),
        ),
    ]
