# Generated by Django 5.2 on 2025-05-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("governanceplatform", "0042_alter_company_address_and_more"),
        ("reporting", "0006_observation_observation_recommendations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observationrecommendation",
            name="sectors",
            field=models.ManyToManyField(
                blank=True, to="governanceplatform.sector", verbose_name="Sectors"
            ),
        ),
    ]
