# Generated by Django 5.2.9 on 2025-12-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0007_alter_observationrecommendation_sectors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sectorreportconfiguration",
            name="number_of_year",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3")],
                verbose_name="Number of years to compare",
            ),
        ),
    ]
