# Generated by Django 5.2.9 on 2025-12-11 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0008_alter_sectorreportconfiguration_number_of_year"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="servicestat",
            options={
                "verbose_name": "Risk analysis stats",
                "verbose_name_plural": "Risk analysis stats",
            },
        ),
    ]
