# Generated by Django 5.1.2 on 2024-11-29 06:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0008_remove_riskanalysisjson_data_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sectorreportconfiguration",
            name="company",
        ),
        migrations.AddField(
            model_name="observationrecommendation",
            name="creation_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Creation date"
            ),
        ),
        migrations.RemoveField(
            model_name='observation',
            name='observation_recommendations',
        ),
        migrations.DeleteModel(
            name="ObservationRecommendationSelection",
        ),
        migrations.AddField(
            model_name='observation',
            name='observation_recommendations',
            field=models.ManyToManyField(verbose_name="Observation recommendations", to="reporting.ObservationRecommendation"),
        ),
    ]
