# Generated by Django 5.1.2 on 2024-12-04 13:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "governanceplatform",
            "0036_alter_functionality_type_delete_sectorcompanycontact",
        ),
        ("reporting", "0009_remove_sectorreportconfiguration_company_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RiskAnalysisJson",
            new_name="CompanyReporting",
        ),
        migrations.RenameField(
            model_name="observation",
            old_name="risk_analysis",
            new_name="company_reporting",
        ),
        migrations.RenameField(
            model_name="servicestat",
            old_name="risk_analysis",
            new_name="company_reporting",
        ),
    ]
