# Generated by Django 5.2.11 on 2026-03-11 08:31

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governanceplatform", "0057_company_sectors"),
        ("reporting", "0010_configuration_color_template"),
        ("securityobjectives", "0030_maturitylevel_color"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                ("updated_at", models.DateTimeField(verbose_name="Updated at")),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=255,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "years",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        size=None,
                        verbose_name="Years",
                    ),
                ),
                (
                    "threshold_for_high_risk",
                    models.IntegerField(
                        null=True, verbose_name="High risk rate threshold"
                    ),
                ),
                (
                    "top_ranking",
                    models.PositiveSmallIntegerField(
                        choices=[(3, "Top 3"), (5, "Top 5"), (10, "Top 10")],
                        null=True,
                        verbose_name="Ranking",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
                (
                    "sectors",
                    models.ManyToManyField(
                        blank=True,
                        to="governanceplatform.sector",
                        verbose_name="Sectors",
                    ),
                ),
                (
                    "standard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="securityobjectives.standard",
                        verbose_name="Standard",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
            },
        ),
    ]
