# Generated by Django 5.1.2 on 2024-12-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reporting", "0010_rename_riskanalysisjson_companyreporting_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sectorreportconfiguration",
            name="asset_number_for_top",
        ),
        migrations.RemoveField(
            model_name="sectorreportconfiguration",
            name="asset_recommendation_for_top",
        ),
        migrations.RemoveField(
            model_name="sectorreportconfiguration",
            name="high_risk_number_for_top",
        ),
        migrations.RemoveField(
            model_name="sectorreportconfiguration",
            name="number_of_year_considered",
        ),
        migrations.RemoveField(
            model_name="sectorreportconfiguration",
            name="threat_number_for_top",
        ),
        migrations.RemoveField(
            model_name="sectorreportconfiguration",
            name="vulnerability_number_for_top",
        ),
        migrations.AddField(
            model_name="sectorreportconfiguration",
            name="number_of_year",
            field=models.PositiveSmallIntegerField(
                default=None, verbose_name="Number of year to compare"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sectorreportconfiguration",
            name="reporting_year",
            field=models.PositiveIntegerField(
                default=None, verbose_name="Reporting year"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sectorreportconfiguration",
            name="top_ranking",
            field=models.PositiveSmallIntegerField(
                choices=[(3, "Top 3"), (5, "Top 5"), (10, "Top 10")],
                default=None,
                verbose_name="Ranking",
            ),
            preserve_default=False,
        ),
    ]
