# Generated by Django 5.2.11 on 2026-03-12 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governanceplatform", "0057_company_sectors"),
        ("reporting", "0011_project"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="logreporting",
            name="reporting",
        ),
        migrations.AddField(
            model_name="logreporting",
            name="project",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reporting.project",
            ),
        ),
        migrations.CreateModel(
            name="CompanyProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                (
                    "is_selected",
                    models.BooleanField(default=False, verbose_name="Is selected"),
                ),
                (
                    "has_security_objectives",
                    models.BooleanField(
                        default=False, verbose_name="Has security objectives"
                    ),
                ),
                (
                    "has_risk_assessment",
                    models.BooleanField(
                        default=False, verbose_name="Has risk assessment"
                    ),
                ),
                (
                    "statistic_selected",
                    models.BooleanField(default=False, verbose_name="Statistics"),
                ),
                (
                    "governance_report_selected",
                    models.BooleanField(
                        default=False, verbose_name="Governance report"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="governanceplatform.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reporting.project",
                        verbose_name="Project",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="governanceplatform.sector",
                        verbose_name="Sector",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="companies",
            field=models.ManyToManyField(
                blank=True,
                through="reporting.CompanyProject",
                to="governanceplatform.company",
            ),
        ),
        migrations.AddConstraint(
            model_name="companyproject",
            constraint=models.UniqueConstraint(
                fields=("company", "project", "sector", "year"),
                name="unique_company_project_sector",
            ),
        ),
    ]
