# Generated by Django 5.2.11 on 2026-03-12 11:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reporting",
            "0012_remove_logreporting_reporting_logreporting_project_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="reference_year",
            field=models.PositiveIntegerField(
                default=2026, verbose_name="Reference year"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="selected_file_format",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(),
                default=list,
                size=None,
                verbose_name="Selected file format",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="selected_languages",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(),
                default=list,
                size=None,
                verbose_name="Selected file format",
            ),
        ),
    ]
