# Generated by Django 5.2.11 on 2026-03-12 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reporting",
            "0013_project_reference_year_project_selected_file_format_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="generatedreport",
            name="user",
        ),
        migrations.AddField(
            model_name="generatedreport",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="reporting.project",
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="generatedreport",
            name="timestamp",
            field=models.DateTimeField(auto_now=True, verbose_name="Timestamp"),
        ),
    ]
