# Generated by Django 5.2.11 on 2026-03-12 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0015_clear_generatedreport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generatedreport",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_report",
                to="reporting.project",
                verbose_name="Project",
            ),
        ),
    ]
