# Generated by Django 5.2.11 on 2026-03-17 10:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0016_alter_generatedreport_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="selected_file_format",
            field=models.CharField(
                choices=[("docx", "docx"), ("pdf", "pdf")], verbose_name="Export format"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="selected_languages",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(),
                default=list,
                size=None,
                verbose_name="Languages",
            ),
        ),
    ]
