# Generated by Django 5.2.11 on 2026-03-23 09:42

from django.db import migrations


def clear_logs(apps, schema_editor):
    LogReporting = apps.get_model("reporting", "LogReporting")
    LogReporting.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0017_alter_project_selected_file_format_and_more"),
    ]

    operations = [
        migrations.RunPython(clear_logs),
    ]
