# Generated by Django 5.2.11 on 2026-03-23 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0018_clear_logreporting"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="companyproject",
            options={"ordering": ["company", "sector", "year"]},
        ),
        migrations.AddField(
            model_name="logreporting",
            name="entity_name",
            field=models.CharField(
                default="", max_length=250, verbose_name="Entity name"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="logreporting",
            name="role",
            field=models.CharField(default="", max_length=250, verbose_name="Role"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="logreporting",
            name="project",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reporting.project",
                verbose_name="Project",
            ),
        ),
        migrations.AlterField(
            model_name="logreporting",
            name="timestamp",
            field=models.DateTimeField(auto_now=True, verbose_name="Timestamp"),
        ),
    ]
