# Generated by Django 5.2.12 on 2026-03-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0019_alter_companyproject_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="reference_year",
            field=models.PositiveIntegerField(verbose_name="Base year"),
        ),
        migrations.AlterField(
            model_name="project",
            name="task_status",
            field=models.CharField(
                choices=[
                    ("FAIL", "Failed"),
                    ("DONE", "Successful"),
                    ("ABORT", "Aborted"),
                    ("RUNNING", "Running"),
                ],
                default="DONE",
                max_length=10,
                null=True,
                verbose_name="Task Status",
            ),
        ),
    ]
