# Generated by Django 6.0.5 on 2026-05-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0020_alter_project_reference_year_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="assetdatatranslation",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="observationrecommendationtranslation",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="threatdatatranslation",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="vulnerabilitydatatranslation",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="assetdatatranslation",
            constraint=models.UniqueConstraint(
                fields=("language_code", "master"),
                name="reporting_assetdata_translation_uniq_lang",
            ),
        ),
        migrations.AddConstraint(
            model_name="observationrecommendationtranslation",
            constraint=models.UniqueConstraint(
                fields=("language_code", "master"),
                name="reporting_observationrecommendation_translation_uniq_lang",
            ),
        ),
        migrations.AddConstraint(
            model_name="threatdatatranslation",
            constraint=models.UniqueConstraint(
                fields=("language_code", "master"),
                name="reporting_threatdata_translation_uniq_lang",
            ),
        ),
        migrations.AddConstraint(
            model_name="vulnerabilitydatatranslation",
            constraint=models.UniqueConstraint(
                fields=("language_code", "master"),
                name="reporting_vulnerabilitydata_translation_uniq_lang",
            ),
        ),
    ]
