# Generated by Django 5.1.2 on 2024-11-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("securityobjectives", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="securityobjectivesinstandard",
            name="priority",
            field=models.IntegerField(default=0),
        ),
    ]
