# Generated by Django 5.1.2 on 2024-10-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "securityobjectives",
            "0002_alter_securitymeasureanswer_security_measure_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="standardanswer",
            name="is_finished",
        ),
        migrations.RemoveField(
            model_name="standardanswer",
            name="is_reviewed",
        ),
        migrations.AddField(
            model_name="standardanswer",
            name="status",
            field=models.CharField(
                choices=[
                    ("UNDE", "Not submitted"),
                    ("DELIV", "Submitted, but review not yet completed"),
                    ("PASS", "Review passed"),
                    ("FAIL", "Review failed"),
                    ("OUT", "Not submitted and deadline exceeded"),
                ],
                default="UNDE",
                max_length=5,
                verbose_name="Status",
            ),
        ),
    ]
