# Generated by Django 5.1.7 on 2025-03-28 09:13

import django.db.models.constraints
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governanceplatform", "0041_alter_company_address_and_more"),
        ("securityobjectives", "0003_alter_standardanswer_status"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="securityobjective",
            name="Unique_unique_code",
        ),
        migrations.AddConstraint(
            model_name="securityobjective",
            constraint=models.UniqueConstraint(
                deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                fields=("unique_code", "creator"),
                name="Unique_unique_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="securityobjectivesinstandard",
            constraint=models.UniqueConstraint(
                fields=("security_objective", "standard"),
                name="unique_security_objective_per_standard",
            ),
        ),
    ]
