# Generated by Django 5.1.2 on 2024-10-28 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("securityobjectives", "0004_maturitylevel_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityObjectiveStatus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_REVIEWED", "Not reviewed"),
                            ("PASS", "Pass"),
                            ("FAIL", "Fail"),
                        ],
                        default="UNDE",
                        verbose_name="Status",
                    ),
                ),
                (
                    "security_objective",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="securityobjectives.securitymeasure",
                    ),
                ),
                (
                    "standard_answer",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="securityobjectives.standardanswer",
                    ),
                ),
            ],
        ),
    ]
