# Generated by Django 5.1.2 on 2024-10-28 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("securityobjectives", "0005_securityobjectivestatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="securityobjectivestatus",
            name="security_objective",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="securityobjectives.securityobjective",
            ),
        ),
    ]
