# Generated by Django 5.2.3 on 2025-07-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "securityobjectives",
            "0006_logstandardanswer_entity_name_logstandardanswer_role",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="securityobjectivestatus",
            name="actions",
            field=models.TextField(
                blank=True, default=None, null=True, verbose_name="Planned actions"
            ),
        ),
    ]
