# Generated by Django 5.1.2 on 2024-10-30 08:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("securityobjectives", "0006_alter_securityobjectivestatus_security_objective"),
    ]

    operations = [
        migrations.RenameField(
            model_name="standardanswer",
            old_name="standard_notification_date",
            new_name="last_update",
        ),
    ]
