# Generated by Django 5.1.2 on 2024-10-30 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "securityobjectives",
            "0007_rename_standard_notification_date_standardanswer_last_update",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="standardanswer",
            name="submit_date",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
