# Generated by Django 5.2.5 on 2025-08-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("securityobjectives", "0007_securityobjectivestatus_actions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="securityobjectivestatus",
            name="actions",
            field=models.TextField(
                blank=True, default=None, null=True, verbose_name="Planned Measures"
            ),
        ),
    ]
