# Generated by Django 5.1.2 on 2024-10-31 07:40

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governanceplatform", "0030_scriptlogentry"),
        ("securityobjectives", "0008_standardanswer_submit_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityObjectiveEmail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "creator_name",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=255,
                        null=True,
                        verbose_name="Creator name",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="governanceplatform.regulator",
                        verbose_name="Creator",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email template",
                "verbose_name_plural": "Email templates",
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name="standard",
            name="security_objective_status_changed_email",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="security_objective_status_changed_email",
                to="securityobjectives.securityobjectiveemail",
                verbose_name="Email for status change",
            ),
        ),
        migrations.AddField(
            model_name="standard",
            name="submission_email",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="security_objective_submission_email",
                to="securityobjectives.securityobjectiveemail",
                verbose_name="Submission e-mail",
            ),
        ),
        migrations.CreateModel(
            name="SecurityObjectiveEmailTranslation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("subject", models.CharField(max_length=255, verbose_name="Subject")),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="securityobjectives.securityobjectiveemail",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email template Translation",
                "db_table": "securityobjectives_securityobjectiveemail_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
