# Generated by Django 5.1.2 on 2024-10-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("securityobjectives", "0008_standardanswer_submit_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="securityobjectivestatus",
            name="score",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
