# Generated by Django 5.2.6 on 2025-09-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("securityobjectives", "0008_alter_securityobjectivestatus_actions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="standardanswer",
            name="status",
            field=models.CharField(
                choices=[
                    ("UNDE", "Unsubmitted"),
                    ("DELIV", "Under review"),
                    ("PASS", "Passed"),
                    ("PASSM", "Passed and sent"),
                    ("FAIL", "Revision required"),
                    ("FAILM", "Revision required and sent"),
                ],
                default="UNDE",
                max_length=5,
                verbose_name="Status",
            ),
        ),
    ]
