# Generated by Django 5.1.2 on 2024-10-31 09:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("securityobjectives", "0009_securityobjectiveemail_and_more"),
        ("securityobjectives", "0009_securityobjectivestatus_score"),
    ]

    operations = []
