# Generated by Django 5.2.6 on 2025-09-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("securityobjectives", "0009_alter_standardanswer_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="securityobjectivestatus",
            name="is_completely_filled_out",
            field=models.BooleanField(
                default=False, verbose_name="It is completely filled out"
            ),
        ),
    ]
