# Generated by Django 5.2.7 on 2025-11-13 12:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def populate_standard_group(apps, schema_editor):
    StandardAnswer = apps.get_model("securityobjectives", "StandardAnswer")
    StandardAnswerGroup = apps.get_model("securityobjectives", "StandardAnswerGroup")

    for sa in StandardAnswer.objects.all():
        sag = StandardAnswerGroup.objects.create()
        sag.save()
        sa.group = sag
        sa.save()


class Migration(migrations.Migration):

    dependencies = [
        ("securityobjectives", "0010_securityobjectivestatus_is_completely_filled_out"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StandardAnswerGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "contact_user",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Contact user",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="standardanswer",
            name="group",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="securityobjectives.standardanswergroup",
                verbose_name="Group",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(populate_standard_group),
        migrations.AlterField(
            model_name="standardanswer",
            name="group",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="securityobjectives.standardanswergroup",
                verbose_name="Group",
            ),
            preserve_default=False,
        ),
    ]
