# Generated by Django 5.1.2 on 2024-10-31 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("securityobjectives", "0010_merge_20241031_1017"),
    ]

    operations = [
        migrations.AlterField(
            model_name="securityobjectivestatus",
            name="status",
            field=models.CharField(
                choices=[
                    ("NOT_REVIEWED", "Not reviewed"),
                    ("PASS", "Pass"),
                    ("FAIL", "Fail"),
                ],
                default="NOT_REVIEWED",
                verbose_name="Status",
            ),
        ),
    ]
