# Generated by Django 5.2.7 on 2025-11-14 09:42

from django.db import migrations, models
from django.utils.translation import activate


def populate_group_id(apps, schema_editor):
    activate("en")
    StandardAnswer = apps.get_model("securityobjectives", "StandardAnswer")
    index_by_company = {}
    for sa in StandardAnswer.objects.all():
        group = sa.group
        company_for_ref = (
            sa.submitter_company.identifier if sa.submitter_company else ""
        )
        framework_for_ref = (
            sa.standard.label[:10] if sa.standard and sa.standard.label else ""
        )
        sector = sa.sectors.first()
        sector_for_ref = sector.parent.acronym[:3] if sector and sector.parent else ""
        subsector_for_ref = sector.acronym[:3] if sector else ""
        company_key = str(sa.submitter_company.id) if sa.submitter_company else ""
        company_key = (
            company_key
            + sector_for_ref
            + subsector_for_ref
            + str(sa.year_of_submission)
        )
        if company_key not in index_by_company:
            index_by_company[company_key] = 0
        else:
            index_by_company[company_key] += 1
        group_by_company = index_by_company[company_key]
        number_of_group = f"{group_by_company:04}"
        group.group_id = (
            f"{company_for_ref}_{framework_for_ref}_{sector_for_ref}_{subsector_for_ref}_"
            f"{number_of_group}_{sa.year_of_submission}"
        )
        group.save()


class Migration(migrations.Migration):

    dependencies = [
        ("securityobjectives", "0011_standardanswergroup_standardanswer_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="standardanswergroup",
            name="group_id",
            field=models.CharField(null=True, max_length=33, verbose_name="Group ID"),
            preserve_default=False,
        ),
        migrations.RunPython(populate_group_id),
        migrations.AlterField(
            model_name="standardanswergroup",
            name="group_id",
            field=models.CharField(max_length=33, verbose_name="Group ID"),
        ),
    ]
