# Generated by Django 5.2.8 on 2025-11-25 09:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governanceplatform", "0055_merge_20251124_1424"),
        ("securityobjectives", "0012_standardanswergroup_group_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="standardanswer",
            name="last_update",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Last update"
            ),
        ),
        migrations.AlterField(
            model_name="standardanswer",
            name="submit_date",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="Submission date"
            ),
        ),
        migrations.AlterField(
            model_name="standardanswer",
            name="submitter_company",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="governanceplatform.company",
                verbose_name="Submitter",
            ),
        ),
        migrations.AlterField(
            model_name="standardanswer",
            name="submitter_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Submitter",
            ),
        ),
        migrations.AlterField(
            model_name="standardanswer",
            name="year_of_submission",
            field=models.PositiveIntegerField(verbose_name="Year of submission"),
        ),
    ]
