# Generated by Django 5.1.2 on 2024-11-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("governanceplatform", "0030_scriptlogentry"),
        (
            "securityobjectives",
            "0012_rename_comment_securitymeasureanswer_justification_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="securitymeasureanswer",
            name="sectors",
        ),
        migrations.AddField(
            model_name="standardanswer",
            name="sectors",
            field=models.ManyToManyField(
                to="governanceplatform.sector", verbose_name="Sectors"
            ),
        ),
    ]
