# Generated by Django 5.2.8 on 2025-11-25 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("securityobjectives", "0013_alter_standardanswer_last_update_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="domain",
            options={"verbose_name": "Domain", "verbose_name_plural": "Domains"},
        ),
        migrations.AlterModelOptions(
            name="domaintranslation",
            options={
                "default_permissions": (),
                "managed": True,
                "verbose_name": "Domain Translation",
            },
        ),
        migrations.AlterModelOptions(
            name="maturitylevel",
            options={
                "verbose_name": "Maturity level",
                "verbose_name_plural": "Maturity levels",
            },
        ),
        migrations.AlterModelOptions(
            name="maturityleveltranslation",
            options={
                "default_permissions": (),
                "managed": True,
                "verbose_name": "Maturity level Translation",
            },
        ),
        migrations.AlterModelOptions(
            name="securitymeasure",
            options={
                "verbose_name": "Security Measure",
                "verbose_name_plural": "Security Measures",
            },
        ),
        migrations.AlterModelOptions(
            name="securitymeasuretranslation",
            options={
                "default_permissions": (),
                "managed": True,
                "verbose_name": "Security Measure Translation",
            },
        ),
        migrations.AlterModelOptions(
            name="securityobjective",
            options={
                "verbose_name": "Security Objective",
                "verbose_name_plural": "Security Objectives",
            },
        ),
        migrations.AlterModelOptions(
            name="securityobjectivetranslation",
            options={
                "default_permissions": (),
                "managed": True,
                "verbose_name": "Security Objective Translation",
            },
        ),
        migrations.AlterModelOptions(
            name="standard",
            options={"verbose_name": "Standard", "verbose_name_plural": "Standards"},
        ),
        migrations.AlterModelOptions(
            name="standardtranslation",
            options={
                "default_permissions": (),
                "managed": True,
                "verbose_name": "Standard Translation",
            },
        ),
    ]
