# Generated by Django 5.2.9 on 2025-12-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "securityobjectives",
            "0014_alter_domain_options_alter_domaintranslation_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="securityobjectivestatus",
            name="status",
            field=models.CharField(
                choices=[
                    ("NOT_REVIEWED", "Not reviewed"),
                    ("PASS", "Passed"),
                    ("FAIL", "Fail"),
                ],
                default="NOT_REVIEWED",
                verbose_name="Status",
            ),
        ),
    ]
