# Generated by Django 5.1.2 on 2024-11-07 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governanceplatform", "0031_functionality_type_functionality_unique_type"),
        ("securityobjectives", "0014_standardanswer_deadline_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="governanceplatform.regulator",
                verbose_name="Creator",
            ),
        ),
        migrations.AddField(
            model_name="domain",
            name="creator_name",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="Creator name",
            ),
        ),
        migrations.AddField(
            model_name="maturitylevel",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="governanceplatform.regulator",
                verbose_name="Creator",
            ),
        ),
        migrations.AddField(
            model_name="maturitylevel",
            name="creator_name",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="Creator name",
            ),
        ),
        migrations.AddField(
            model_name="securitymeasure",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="governanceplatform.regulator",
                verbose_name="Creator",
            ),
        ),
        migrations.AddField(
            model_name="securitymeasure",
            name="creator_name",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="Creator name",
            ),
        ),
        migrations.AddField(
            model_name="securityobjective",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="governanceplatform.regulator",
                verbose_name="Creator",
            ),
        ),
        migrations.AddField(
            model_name="securityobjective",
            name="creator_name",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="Creator name",
            ),
        ),
    ]
