# Generated by Django 5.2.9 on 2025-12-22 07:57

import django.db.models.deletion
from django.db import migrations, models


def populate_standard(apps, schema_editor):
    Standard = apps.get_model("securityobjectives", "Standard")
    Domain = apps.get_model("securityobjectives", "Domain")
    MaturityLevel = apps.get_model("securityobjectives", "MaturityLevel")

    for d in Domain.objects.all():
        first_so = d.securityobjective.first()
        standard = first_so.securityobjectivesinstandard_set.first().standard
        if standard is None:
            standard = Standard.objects.all().first()
        d.standard = standard
        d.save()

    for ml in MaturityLevel.objects.all():
        first_so = ml.securitymeasure_set.first().security_objective
        standard = first_so.securityobjectivesinstandard_set.first().standard
        if standard is None:
            standard = Standard.objects.all().first()
        ml.standard = standard
        ml.save()


class Migration(migrations.Migration):

    dependencies = [
        ("securityobjectives", "0015_alter_securityobjectivestatus_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="standard",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="securityobjectives.standard",
            ),
        ),
        migrations.AddField(
            model_name="maturitylevel",
            name="standard",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="securityobjectives.standard",
            ),
        ),
        migrations.RunPython(populate_standard),
        migrations.AlterField(
            model_name="domain",
            name="standard",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="securityobjectives.standard",
            ),
        ),
        migrations.AlterField(
            model_name="maturitylevel",
            name="standard",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="securityobjectives.standard",
            ),
        ),
    ]
