# Generated by Django 5.2.9 on 2025-12-23 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("securityobjectives", "0017_alter_standardanswergroup_group_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="standard",
            name="security_objective_closure_email",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="security_objective_closure_email",
                to="securityobjectives.securityobjectiveemail",
                verbose_name="Email for closure",
            ),
        ),
    ]
