# Generated by Django 5.2.9 on 2025-12-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("securityobjectives", "0018_standard_security_objective_closure_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="securityobjectiveemailtranslation",
            name="content",
            field=models.TextField(
                help_text="Available placeholders: #SO_REFERENCE#,\n                #DEADLINE#",
                verbose_name="Content",
            ),
        ),
    ]
