# Generated by Django 5.2.9 on 2026-01-05 13:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governanceplatform", "0055_settingsdummy"),
        ("securityobjectives", "0019_alter_securityobjectiveemailtranslation_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain",
            name="position",
            field=models.IntegerField(default=0, verbose_name="Position"),
        ),
        migrations.AlterField(
            model_name="domain",
            name="standard",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="securityobjectives.standard",
                verbose_name="Standard",
            ),
        ),
        migrations.AlterField(
            model_name="domaintranslation",
            name="label",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="Label",
            ),
        ),
        migrations.AlterField(
            model_name="maturitylevel",
            name="level",
            field=models.IntegerField(default=0, verbose_name="Level"),
        ),
        migrations.AlterField(
            model_name="maturityleveltranslation",
            name="label",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="Label",
            ),
        ),
        migrations.AlterField(
            model_name="securitymeasure",
            name="maturity_level",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="securityobjectives.maturitylevel",
                verbose_name="Level",
            ),
        ),
        migrations.AlterField(
            model_name="securitymeasure",
            name="position",
            field=models.IntegerField(default=0, verbose_name="Position"),
        ),
        migrations.AlterField(
            model_name="securitymeasure",
            name="security_objective",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="securityobjectives.securityobjective",
                verbose_name="Security Objective",
            ),
        ),
        migrations.AlterField(
            model_name="securitymeasureanswer",
            name="justification",
            field=models.TextField(verbose_name="Justification"),
        ),
        migrations.AlterField(
            model_name="securitymeasureanswer",
            name="review_comment",
            field=models.TextField(verbose_name="Review comment"),
        ),
        migrations.AlterField(
            model_name="securitymeasureanswer",
            name="security_measure",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="securitymeasureanswers",
                to="securityobjectives.securitymeasure",
                verbose_name="Security Measure",
            ),
        ),
        migrations.AlterField(
            model_name="securitymeasureanswer",
            name="security_measure_notification_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Notification date"
            ),
        ),
        migrations.AlterField(
            model_name="securitymeasureanswer",
            name="standard_answer",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="securitymeasureanswers",
                to="securityobjectives.standardanswer",
                verbose_name="Standard Answer",
            ),
        ),
        migrations.AlterField(
            model_name="securitymeasuretranslation",
            name="description",
            field=models.TextField(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="securitymeasuretranslation",
            name="evidence",
            field=models.TextField(verbose_name="Evidence"),
        ),
        migrations.AlterField(
            model_name="securityobjective",
            name="domain",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="securityobjective",
                to="securityobjectives.domain",
                verbose_name="Domain",
            ),
        ),
        migrations.AlterField(
            model_name="securityobjective",
            name="unique_code",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="Unique code",
            ),
        ),
        migrations.AlterField(
            model_name="securityobjectivesinstandard",
            name="position",
            field=models.IntegerField(default=0, verbose_name="Position"),
        ),
        migrations.AlterField(
            model_name="securityobjectivesinstandard",
            name="priority",
            field=models.IntegerField(default=0, verbose_name="Priority"),
        ),
        migrations.AlterField(
            model_name="securityobjectivesinstandard",
            name="security_objective",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="securityobjectives.securityobjective",
                verbose_name="Security Objective",
            ),
        ),
        migrations.AlterField(
            model_name="securityobjectivestatus",
            name="score",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=4, verbose_name="Score"
            ),
        ),
        migrations.AlterField(
            model_name="securityobjectivestatus",
            name="security_objective",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="securityobjectives.securityobjective",
                verbose_name="Security Objective",
            ),
        ),
        migrations.AlterField(
            model_name="securityobjectivestatus",
            name="standard_answer",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="securityobjectives.standardanswer",
                verbose_name="Security objectives statement",
            ),
        ),
        migrations.AlterField(
            model_name="securityobjectivetranslation",
            name="description",
            field=models.TextField(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="securityobjectivetranslation",
            name="objective",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="Objective",
            ),
        ),
        migrations.AlterField(
            model_name="standard",
            name="regulation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="governanceplatform.regulation",
                verbose_name="Regulation",
            ),
        ),
        migrations.AlterField(
            model_name="standard",
            name="regulator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="governanceplatform.regulator",
                verbose_name="Regulator",
            ),
        ),
        migrations.AlterField(
            model_name="standard",
            name="security_objectives",
            field=models.ManyToManyField(
                through="securityobjectives.SecurityObjectivesInStandard",
                to="securityobjectives.securityobjective",
                verbose_name="Security objectives",
            ),
        ),
        migrations.AlterField(
            model_name="standardanswer",
            name="creator_company_name",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="Company of creator",
            ),
        ),
        migrations.AlterField(
            model_name="standardanswer",
            name="creator_name",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="Creator name",
            ),
        ),
        migrations.AlterField(
            model_name="standardanswer",
            name="standard",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="standardanswer",
                to="securityobjectives.standard",
                verbose_name="Standard",
            ),
        ),
        migrations.AlterField(
            model_name="standardanswergroup",
            name="notification_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Notification date"
            ),
        ),
        migrations.AlterField(
            model_name="standardtranslation",
            name="description",
            field=models.TextField(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="standardtranslation",
            name="label",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="Label",
            ),
        ),
    ]
