# Generated by Django 5.2.9 on 2026-01-14 10:45

import django.db.models.deletion
from django.db import migrations, models


# avoid migration issue erase all duplicate in securityobjectiveinstandard
def duplicate_so_id(apps, schema_editor):
    SecurityObjectivesInStandard = apps.get_model(
        "securityobjectives", "SecurityObjectivesInStandard"
    )
    SecurityObjective = apps.get_model("securityobjectives", "SecurityObjective")
    for so in SecurityObjective.objects.all():
        soiss = (
            SecurityObjectivesInStandard.objects.filter(security_objective=so)
            .order_by("standard__pk")
            .distinct()
        )
        for index, sois in enumerate(soiss):
            if index > 0:
                sois.delete()


class Migration(migrations.Migration):

    dependencies = [
        (
            "securityobjectives",
            "0020_alter_domain_position_alter_domain_standard_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(duplicate_so_id),
        migrations.AlterField(
            model_name="securityobjectivesinstandard",
            name="security_objective",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="standard_link",
                to="securityobjectives.securityobjective",
                verbose_name="Security Objective",
            ),
        ),
        migrations.AlterField(
            model_name="securityobjectivesinstandard",
            name="standard",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="security_objectives_set",
                to="securityobjectives.standard",
            ),
        ),
    ]
