# Generated by Django 5.2.9 on 2026-01-15 10:36

import django.db.models.deletion
from django.db import migrations, models


# avoid migration issue erase all duplicate in securityobjectiveinstandard
def migrate_company(apps, schema_editor):
    StandardAnswerGroup = apps.get_model("securityobjectives", "StandardAnswerGroup")
    for sag in StandardAnswerGroup.objects.all():
        standard = sag.standardanswer_set.first()
        if standard is not None:
            sag.company = standard.submitter_company
            sag.save()


class Migration(migrations.Migration):

    dependencies = [
        ("governanceplatform", "0055_settingsdummy"),
        (
            "securityobjectives",
            "0021_alter_securityobjectivesinstandard_security_objective_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="standardanswergroup",
            name="company",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="governanceplatform.company",
                verbose_name="Company",
            ),
        ),
        migrations.RunPython(migrate_company),
        migrations.RemoveField(
            model_name="standardanswergroup",
            name="contact_user",
        ),
    ]
