# Generated by Django 5.2.10 on 2026-01-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("securityobjectives", "0022_standardanswergroup_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logstandardanswer",
            name="action",
            field=models.CharField(max_length=250, verbose_name="Action performed"),
        ),
    ]
