# Generated by Django 5.2.10 on 2026-01-20 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("securityobjectives", "0023_alter_logstandardanswer_action"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="standardanswer",
            name="deadline",
        ),
    ]
