# Generated by Django 5.2.10 on 2026-01-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("securityobjectives", "0024_remove_standardanswer_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="securityobjectiveemailtranslation",
            name="content",
            field=models.TextField(
                help_text="Available placeholders: #SO_REFERENCE#",
                verbose_name="Content",
            ),
        ),
    ]
