# Generated by Django 5.2.10 on 2026-02-10 09:41

from django.db import migrations


def set_role_from_user_group(apps, schema_editor):
    LogStandardAnswer = apps.get_model("securityobjectives", "LogStandardAnswer")

    for log in LogStandardAnswer.objects.select_related("user"):
        if not log.user:
            continue

        groups = log.user.groups.all()

        if groups.exists():
            log.role = groups.first().name
        else:
            log.role = ""

        log.save(update_fields=["role"])


class Migration(migrations.Migration):

    dependencies = [
        ("securityobjectives", "0025_alter_securityobjectiveemailtranslation_content"),
    ]

    operations = [
        migrations.RunPython(set_role_from_user_group),
    ]
