# Generated by Django 5.2.11 on 2026-02-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("securityobjectives", "0026_update_logreportread_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="standardanswer",
            name="creation_date",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="Creation date"
            ),
        ),
    ]
