# Generated by Django 5.2.11 on 2026-02-13 13:17

from django.db import migrations, models


def populate_creation_date(apps, schema_editor):
    StandardAnswer = apps.get_model("securityobjectives", "StandardAnswer")

    # Copy last_update into creation_date where it is null
    StandardAnswer.objects.filter(creation_date__isnull=True).update(
        creation_date=models.F("last_update")
    )


class Migration(migrations.Migration):

    dependencies = [
        ("securityobjectives", "0027_standardanswer_creation_date"),
    ]

    operations = [
        migrations.RunPython(populate_creation_date),
    ]
