# Generated by Django 5.2.11 on 2026-02-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("securityobjectives", "0028_auto_20260213_1429"),
    ]

    operations = [
        migrations.AlterField(
            model_name="standardanswer",
            name="creation_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creation date"),
        ),
        migrations.AlterField(
            model_name="standardanswer",
            name="last_update",
            field=models.DateTimeField(auto_now=True, verbose_name="Last update"),
        ),
    ]
