# Generated by Django 5.2.11 on 2026-03-04 13:26

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("securityobjectives", "0029_alter_standardanswer_creation_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="maturitylevel",
            name="color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF",
                help_text="Color used in reporting module (hexadecimal format)",
                image_field=None,
                max_length=25,
                samples=None,
                verbose_name="Color",
            ),
        ),
    ]
