# Generated by Django 5.2.11 on 2026-03-16 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("securityobjectives", "0030_maturitylevel_color"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="domain",
            options={
                "ordering": ["position"],
                "verbose_name": "Domain",
                "verbose_name_plural": "Domains",
            },
        ),
        migrations.AlterModelOptions(
            name="securityobjectivesinstandard",
            options={"ordering": ["position"]},
        ),
    ]
