# Generated by Django 5.2.11 on 2026-03-17 08:40

import django.db.models.constraints
from django.db import migrations, models
from django.db.models import Count, Min


def delete_duplicate_maturity_level_standard(apps, schema_editor):
    MaturityLevel = apps.get_model("securityobjectives", "MaturityLevel")

    # 1. find duplicates
    duplicates = (
        MaturityLevel.objects.values("standard", "level")
        .annotate(count=Count("id"), min_id=Min("id"))
        .filter(count__gt=1)
    )

    ids_to_delete = []
    for entry in duplicates:
        ids = (
            MaturityLevel.objects.filter(
                standard=entry["standard"],
                level=entry["level"],
            )
            .exclude(id=entry["min_id"])
            .values_list("id", flat=True)
        )
        ids_to_delete.extend(ids)

    MaturityLevel.objects.filter(id__in=ids_to_delete).delete()


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ("governanceplatform", "0057_company_sectors"),
        ("securityobjectives", "0031_alter_domain_options_and_more"),
    ]

    operations = [
        migrations.RunPython(delete_duplicate_maturity_level_standard),
        migrations.RunSQL("COMMIT;"),
        migrations.AddConstraint(
            model_name="maturitylevel",
            constraint=models.UniqueConstraint(
                deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                fields=("level", "standard"),
                name="level_standard",
            ),
        ),
    ]
