# Generated by Django 6.0.5 on 2026-05-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("securityobjectives", "0032_maturitylevel_level_standard"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="domaintranslation",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="maturityleveltranslation",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="securitymeasuretranslation",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="securityobjectiveemailtranslation",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="securityobjectivetranslation",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="standardtranslation",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="domaintranslation",
            constraint=models.UniqueConstraint(
                fields=("language_code", "master"),
                name="securityobjectives_domain_translation_uniq_lang",
            ),
        ),
        migrations.AddConstraint(
            model_name="maturityleveltranslation",
            constraint=models.UniqueConstraint(
                fields=("language_code", "master"),
                name="securityobjectives_maturitylevel_translation_uniq_lang",
            ),
        ),
        migrations.AddConstraint(
            model_name="securitymeasuretranslation",
            constraint=models.UniqueConstraint(
                fields=("language_code", "master"),
                name="securityobjectives_securitymeasure_translation_uniq_lang",
            ),
        ),
        migrations.AddConstraint(
            model_name="securityobjectiveemailtranslation",
            constraint=models.UniqueConstraint(
                fields=("language_code", "master"),
                name="securityobjectives_securityobjectiveemail_translation_uniq_lang",
            ),
        ),
        migrations.AddConstraint(
            model_name="securityobjectivetranslation",
            constraint=models.UniqueConstraint(
                fields=("language_code", "master"),
                name="securityobjectives_securityobjective_translation_uniq_lang",
            ),
        ),
        migrations.AddConstraint(
            model_name="standardtranslation",
            constraint=models.UniqueConstraint(
                fields=("language_code", "master"),
                name="securityobjectives_standard_translation_uniq_lang",
            ),
        ),
    ]
