# Generated by Django 4.2.1 on 2023-06-26 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("governanceplatform", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_regulator",
        ),
    ]
