# Generated by Django 4.2.2 on 2023-06-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governanceplatform", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="types",
            field=models.ManyToManyField(to="governanceplatform.operatortype"),
        ),
        migrations.AddConstraint(
            model_name="companyadministrator",
            constraint=models.UniqueConstraint(
                fields=("user", "company"), name="unique_CompanyAdministrator"
            ),
        ),
    ]
