# Generated by Django 4.2.5 on 2023-09-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0001_initial"),
        ("governanceplatform", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sector",
            name="accronym",
            field=models.CharField(blank=True, default=None, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="sector",
            name="specific_impact",
            field=models.ManyToManyField(
                blank=True, default=None, to="incidents.impact"
            ),
        ),
    ]
