# Generated by Django 4.2.5 on 2023-10-27 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("governanceplatform", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyUser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_company_administrator",
                    models.BooleanField(default=False, verbose_name="is administrator"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="governanceplatform.company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Company user",
                "verbose_name_plural": "Company user",
            },
        ),
        migrations.CreateModel(
            name="RegulatorUser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_regulator_administrator",
                    models.BooleanField(default=False, verbose_name="is administrator"),
                ),
                (
                    "regulator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="governanceplatform.regulator",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Regulator user",
                "verbose_name_plural": "Regulator users",
            },
        ),
        migrations.DeleteModel(
            name="CompanyAdministrator",
        ),
        migrations.AlterField(
            model_name="user",
            name="companies",
            field=models.ManyToManyField(
                through="governanceplatform.CompanyUser",
                to="governanceplatform.company",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatoruser",
            constraint=models.UniqueConstraint(
                fields=("user", "regulator"), name="unique_RegulatorUser"
            ),
        ),
        migrations.AddConstraint(
            model_name="companyuser",
            constraint=models.UniqueConstraint(
                fields=("user", "company"), name="unique_CompanyUser"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="regulators",
            field=models.ManyToManyField(
                through="governanceplatform.RegulatorUser",
                to="governanceplatform.regulator",
            ),
        ),
    ]
