# Generated by Django 4.2.5 on 2023-09-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governanceplatform", "0002_sector_accronym_sector_specific_impact"),
    ]

    operations = [
        migrations.AddField(
            model_name="services",
            name="accronym",
            field=models.CharField(blank=True, default=None, max_length=4, null=True),
        ),
    ]
