# Generated by Django 4.2.1 on 2023-05-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governanceplatform", "0002_rename_adress_company_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalToken",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=255)),
                ("module_path", models.CharField(max_length=255)),
                ("module_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name="company",
            options={"verbose_name": "Company", "verbose_name_plural": "Companies"},
        ),
        migrations.AlterModelOptions(
            name="sector",
            options={"verbose_name": "Sector", "verbose_name_plural": "Sectors"},
        ),
        migrations.AddField(
            model_name="user",
            name="is_administrator",
            field=models.BooleanField(default=False),
        ),
    ]
