# Generated by Django 4.2 on 2023-09-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governanceplatform', '0003_services_accronym'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email_for_notification',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True, verbose_name='email address'),
        ),
    ]
