# Generated by Django 4.2 on 2023-10-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "governanceplatform",
            "0003_alter_company_phone_number_alter_user_phone_number",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="identifier",
            field=models.CharField(max_length=4, verbose_name="Identifier"),
        ),
    ]
