# Generated by Django 4.2.5 on 2023-11-08 13:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("governanceplatform", "0003_companyuser_regulatoruser_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sector",
            name="specific_impact",
        ),
    ]
