# Generated by Django 4.2.5 on 2023-11-16 17:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("governanceplatform", "0004_remove_sector_specific_impact"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="monarc_path",
        ),
        migrations.RemoveField(
            model_name="regulator",
            name="monarc_path",
        ),
    ]
