# Generated by Django 4.2.5 on 2023-09-19 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0001_initial"),
        ("governanceplatform", "0004_company_email_for_notification"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Services",
            new_name="Service",
        ),
        migrations.RenameModel(
            old_name="ServicesTranslation",
            new_name="ServiceTranslation",
        ),
        migrations.AlterModelTable(
            name="servicetranslation",
            table="governanceplatform_service_translation",
        ),
    ]
