# Generated by Django 4.2.2 on 2023-07-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governanceplatform", "0004_alter_user_companies_alter_user_sectors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="companies",
            field=models.ManyToManyField(
                through="governanceplatform.CompanyAdministrator",
                to="governanceplatform.company",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="sectors",
            field=models.ManyToManyField(
                through="governanceplatform.SectorContact",
                to="governanceplatform.sector",
            ),
        ),
    ]
