# Generated by Django 4.2 on 2024-02-01 09:28

from django.db import migrations
import django_countries.fields
from governanceplatform.models import Company


class Migration(migrations.Migration):

    dependencies = [
        ('governanceplatform', '0005_remove_company_monarc_path_and_more'),
    ]

    for obj in Company.objects.all():
        obj.country = str(obj.country)[0:2]
        obj.save()

    operations = [
        migrations.AlterField(
            model_name='company',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
