# Generated by Django 5.0.6 on 2024-07-23 09:52

from django.db import migrations


def copy_data_to_temp_fields(apps, schema_editor):
    Regulator = apps.get_model("governanceplatform", "Regulator")
    for regulator in Regulator.objects.all():
        regulator.temp_name = regulator.name
        regulator.temp_full_name = regulator.full_name
        regulator.temp_description = regulator.description
        regulator.save()


class Migration(migrations.Migration):
    dependencies = [
        (
            "governanceplatform",
            "0005_regulator_temp_description_regulator_temp_full_name_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(copy_data_to_temp_fields),
    ]
