# Generated by Django 4.2.2 on 2023-07-18 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governanceplatform", "0005_alter_user_companies_alter_user_sectors"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ExternalToken",
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user can log into this admin site.",
                verbose_name="staff status",
            ),
        ),
    ]
