# Generated by Django 4.2.5 on 2023-09-26 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("governanceplatform", "0005_rename_services_service_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="proxy_token",
        ),
    ]
