# Generated by Django 4.2.5 on 2023-09-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governanceplatform", "0006_remove_user_proxy_token"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sector",
            old_name="accronym",
            new_name="acronym",
        ),
        migrations.RenameField(
            model_name="service",
            old_name="accronym",
            new_name="acronym",
        ),
        migrations.AlterField(
            model_name="sectortranslation",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="servicetranslation",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Name"),
        ),
    ]
