# Generated by Django 4.2.2 on 2023-07-18 08:31

from django.db import migrations, models

import governanceplatform.helpers


class Migration(migrations.Migration):

    dependencies = [
        ("governanceplatform", "0006_delete_externaltoken_alter_user_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="proxy_token",
            field=models.CharField(
                default=governanceplatform.helpers.generate_token,
                max_length=255,
                null=True,
            ),
        ),
    ]
