# Generated by Django 4.2.2 on 2023-07-18 08:31

import secrets

from django.db import migrations


def generate_token(apps, schema_editor):
    users = apps.get_model("governanceplatform", "user")
    for row in users.objects.all():
        row.proxy_token = secrets.token_urlsafe(32)[:32]
        row.save(update_fields=["proxy_token"])


class Migration(migrations.Migration):
    dependencies = [
        ("governanceplatform", "0007_user_proxy_token"),
    ]

    operations = [
        migrations.RunPython(
            generate_token,
        ),
    ]
