# Generated by Django 4.2 on 2024-02-07 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("governanceplatform", "0007_sector_creator_sector_creator_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="SectorCompanyContact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_sector_contact",
                    models.BooleanField(default=False, verbose_name="Contact person"),
                ),
                (
                    "is_company_administrator",
                    models.BooleanField(default=False, verbose_name="is administrator"),
                ),
            ],
            options={
                "verbose_name": "Sector contact",
                "verbose_name_plural": "Sectors contact",
            },
        ),
        migrations.RemoveField(
            model_name="sectorcontact",
            name="sector",
        ),
        migrations.RemoveField(
            model_name="sectorcontact",
            name="user",
        ),
        migrations.RemoveField(
            model_name="company",
            name="sectors",
        ),
        migrations.AddField(
            model_name="regulatoruser",
            name="sectors",
            field=models.ManyToManyField(to="governanceplatform.sector"),
        ),
        migrations.AlterField(
            model_name="regulator",
            name="email_for_notification",
            field=models.EmailField(
                blank=True,
                default=None,
                max_length=254,
                null=True,
                verbose_name="email address for incident notification",
            ),
        ),
        migrations.DeleteModel(
            name="CompanyUser",
        ),
        migrations.DeleteModel(
            name="SectorContact",
        ),
        migrations.AddField(
            model_name="sectorcompanycontact",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="governanceplatform.company",
            ),
        ),
        migrations.AddField(
            model_name="sectorcompanycontact",
            name="sector",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="governanceplatform.sector",
            ),
        ),
        migrations.AddField(
            model_name="sectorcompanycontact",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="sector_contacts",
            field=models.ManyToManyField(
                through="governanceplatform.SectorCompanyContact",
                to="governanceplatform.sector",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="companies",
            field=models.ManyToManyField(
                through="governanceplatform.SectorCompanyContact",
                to="governanceplatform.company",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="sectors",
            field=models.ManyToManyField(
                through="governanceplatform.SectorCompanyContact",
                to="governanceplatform.sector",
            ),
        ),
        migrations.AddConstraint(
            model_name="sectorcompanycontact",
            constraint=models.UniqueConstraint(
                fields=("user", "sector", "company"), name="unique_SectorCompanyContact"
            ),
        ),
    ]
