# Generated by Django 4.2.1 on 2023-05-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governanceplatform", "0008_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                error_messages={
                    "unique": "A user is already registered with this email address"
                },
                max_length=254,
                unique=True,
                verbose_name="email address",
            ),
        ),
    ]
