# Generated by Django 5.0.7 on 2024-07-23 12:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("governanceplatform", "0008_auto_20240723_1405"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="regulator",
            name="temp_description",
        ),
        migrations.RemoveField(
            model_name="regulator",
            name="temp_full_name",
        ),
        migrations.RemoveField(
            model_name="regulator",
            name="temp_name",
        ),
    ]
