# Generated by Django 4.2.1 on 2023-05-31 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governanceplatform", "0009_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="address",
            field=models.CharField(max_length=255, verbose_name="address"),
        ),
        migrations.AlterField(
            model_name="company",
            name="country",
            field=models.CharField(max_length=64, verbose_name="country"),
        ),
        migrations.AlterField(
            model_name="company",
            name="email",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=100,
                null=True,
                verbose_name="email address",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="identifier",
            field=models.CharField(max_length=64, verbose_name="Identifier"),
        ),
        migrations.AlterField(
            model_name="company",
            name="is_regulator",
            field=models.BooleanField(default=False, verbose_name="Regulator"),
        ),
        migrations.AlterField(
            model_name="company",
            name="monarc_path",
            field=models.CharField(max_length=200, verbose_name="MONARC URL"),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=64, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="company",
            name="phone_number",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=30,
                null=True,
                verbose_name="phone number",
            ),
        ),
        migrations.AlterField(
            model_name="sector",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="governanceplatform.sector",
                verbose_name="parent",
            ),
        ),
        migrations.AlterField(
            model_name="sectoradministration",
            name="is_sector_administrator",
            field=models.BooleanField(default=False, verbose_name="Administrator"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_administrator",
            field=models.BooleanField(default=False, verbose_name="Administrator"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_regulator",
            field=models.BooleanField(default=False, verbose_name="Regulator"),
        ),
    ]
