# Generated by Django 4.2 on 2024-02-21 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "governanceplatform",
            "0009_remove_companyuser_company_remove_companyuser_user_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Cert",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="name")),
                ("country", models.CharField(max_length=64, verbose_name="country")),
                ("address", models.CharField(max_length=255, verbose_name="address")),
                (
                    "email_for_notification",
                    models.EmailField(
                        blank=True,
                        default=None,
                        max_length=254,
                        null=True,
                        verbose_name="email address for incident notification",
                    ),
                ),
                (
                    "full_name",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="full name"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="description"
                    ),
                ),
                (
                    "is_receiving_all_incident",
                    models.BooleanField(
                        default=False, verbose_name="Receive all incident"
                    ),
                ),
            ],
            options={
                "verbose_name": "CERT",
                "verbose_name_plural": "CERTs",
            },
        ),
        migrations.CreateModel(
            name="CertUser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_cert_administrator",
                    models.BooleanField(default=False, verbose_name="is administrator"),
                ),
                (
                    "cert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="governanceplatform.cert",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "CERT user",
                "verbose_name_plural": "CERT users",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="certs",
            field=models.ManyToManyField(
                through="governanceplatform.CertUser", to="governanceplatform.cert"
            ),
        ),
        migrations.AddConstraint(
            model_name="certuser",
            constraint=models.UniqueConstraint(
                fields=("user", "cert"), name="unique_CertUser"
            ),
        ),
    ]
