# Generated by Django 5.0.7 on 2024-07-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("governanceplatform", "0009_remove_regulator_temp_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cert",
            name="temp_description",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="cert",
            name="temp_full_name",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="cert",
            name="temp_name",
            field=models.CharField(default="", max_length=64),
        ),
    ]
