# Generated by Django 4.2.1 on 2023-06-01 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "governanceplatform",
            "0010_alter_company_address_alter_company_country_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
