# Generated by Django 5.0.7 on 2024-07-23 13:12

from django.db import migrations


def copy_data_to_temp_fields(apps, schema_editor):
    Cert = apps.get_model("governanceplatform", "Cert")
    for cert in Cert.objects.all():
        cert.temp_name = cert.name
        cert.temp_full_name = cert.full_name
        cert.temp_description = cert.description
        cert.save()


class Migration(migrations.Migration):
    dependencies = [
        (
            "governanceplatform",
            "0010_cert_temp_description_cert_temp_full_name_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(copy_data_to_temp_fields),
    ]
