# Generated by Django 5.0.7 on 2024-07-23 13:21

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("governanceplatform", "0011_auto_20240723_1512"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cert",
            name="description",
        ),
        migrations.RemoveField(
            model_name="cert",
            name="full_name",
        ),
        migrations.RemoveField(
            model_name="cert",
            name="name",
        ),
        migrations.CreateModel(
            name="CertTranslation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                (
                    "name",
                    models.CharField(default="", max_length=64, verbose_name="name"),
                ),
                (
                    "full_name",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="full name"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="description"
                    ),
                ),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="governanceplatform.cert",
                    ),
                ),
            ],
            options={
                "verbose_name": "CERT Translation",
                "db_table": "governanceplatform_cert_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
        ),
    ]
