# Generated by Django 5.0.7 on 2024-07-23 13:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("governanceplatform", "0014_remove_cert_temp_description_and_more"),
    ]

    operations = [
        migrations.RenameModel("Cert", "Observer"),
        migrations.RenameModel("CertUser", "ObserverUser"),
    ]
