# Generated by Django 5.0.7 on 2024-07-23 13:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("governanceplatform", "0015_auto_20240723_1552"),
    ]

    operations = [
        migrations.RenameField("ObserverUser", "cert", "observer"),
        migrations.RenameField(
            "ObserverUser", "is_cert_administrator", "is_observer_administrator"
        ),
        migrations.RenameField("User", "certs", "observers"),
    ]
