# Generated by Django 5.0.7 on 2024-07-23 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("governanceplatform", "0016_auto_20240723_1556"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CertTranslation",
            new_name="ObserverTranslation",
        ),
        migrations.AlterModelOptions(
            name="observer",
            options={"verbose_name": "Observer", "verbose_name_plural": "Observers"},
        ),
        migrations.AlterModelOptions(
            name="observertranslation",
            options={
                "default_permissions": (),
                "managed": True,
                "verbose_name": "Observer Translation",
            },
        ),
        migrations.AlterModelOptions(
            name="observeruser",
            options={
                "verbose_name": "Observer user",
                "verbose_name_plural": "Observer users",
            },
        ),
        migrations.RemoveConstraint(
            model_name="observeruser",
            name="unique_CertUser",
        ),
        migrations.AlterField(
            model_name="observeruser",
            name="observer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="governanceplatform.observer",
                verbose_name="Observer",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="observers",
            field=models.ManyToManyField(
                through="governanceplatform.ObserverUser",
                to="governanceplatform.observer",
                verbose_name="Observers",
            ),
        ),
        migrations.AddConstraint(
            model_name="observeruser",
            constraint=models.UniqueConstraint(
                fields=("user", "observer"), name="unique_ObserverUser"
            ),
        ),
        migrations.AlterModelTable(
            name="observertranslation",
            table="governanceplatform_observer_translation",
        ),
    ]
