# Generated by Django 5.0.7 on 2024-07-23 14:49

from django.contrib.auth.models import Group
from django.db import migrations


def rename_cert_groups(apps, schema_editor):
    # Renaming groups
    group_renames = {
        "CertAdmin": "ObserverAdmin",
        "CertUser": "ObserverUser",
    }

    for old_name, new_name in group_renames.items():
        try:
            group = Group.objects.get(name=old_name)
            group.name = new_name
            group.save()
        except Group.DoesNotExist:
            pass


class Migration(migrations.Migration):
    dependencies = [
        (
            "governanceplatform",
            "0017_rename_certtranslation_observertranslation_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(rename_cert_groups),
    ]
