# Generated by Django 5.1 on 2024-09-03 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("governanceplatform", "0020_alter_regulator_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="regulator",
            name="is_receiving_all_incident",
        ),
    ]
