# Generated by Django 5.1 on 2024-09-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("governanceplatform", "0021_remove_regulator_is_receiving_all_incident"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sector",
            name="acronym",
            field=models.CharField(
                default="NULL", max_length=4, verbose_name="Acronym"
            ),
            preserve_default=False,
        ),
    ]
