# Generated by Django 5.1 on 2024-09-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("governanceplatform", "0022_alter_sector_acronym"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="acronym",
            field=models.CharField(
                default="NULL", max_length=4, verbose_name="Acronym"
            ),
            preserve_default=False,
        ),
    ]
