# Generated by Django 5.1.1 on 2024-09-26 08:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("governanceplatform", "0027_company_entity_categories_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="observerregulation",
            name="is_spoc",
        ),
    ]
