# Generated by Django 5.1.1 on 2024-10-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governanceplatform", "0028_remove_observerregulation_is_spoc"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="accepted_terms",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="accepted_terms_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
