# Generated by Django 5.1.2 on 2024-10-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governanceplatform", "0029_user_accepted_terms_user_accepted_terms_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScriptLogEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_time",
                    models.DateTimeField(auto_now=True, verbose_name="Action time"),
                ),
                (
                    "action_flag",
                    models.PositiveSmallIntegerField(verbose_name="Action flag"),
                ),
                (
                    "object_id",
                    models.TextField(blank=True, null=True, verbose_name="Object id"),
                ),
                (
                    "object_repr",
                    models.CharField(
                        max_length=200, verbose_name="Object representation"
                    ),
                ),
                (
                    "additional_info",
                    models.TextField(
                        blank=True, null=True, verbose_name="Additional information"
                    ),
                ),
            ],
            options={
                "verbose_name": "Script log entry",
                "verbose_name_plural": "Script log entries",
            },
        ),
    ]
