# Generated by Django 5.1.2 on 2024-11-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governanceplatform", "0031_functionality_type_functionality_unique_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observer",
            name="functionalities",
            field=models.ManyToManyField(
                blank=True,
                to="governanceplatform.functionality",
                verbose_name="Functionalities",
            ),
        ),
    ]
