# Generated by Django 5.1.2 on 2024-11-14 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governanceplatform", "0032_alter_observer_functionalities"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyUser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_company_administrator",
                    models.BooleanField(default=False, verbose_name="is administrator"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="governanceplatform.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "sectors",
                    models.ManyToManyField(
                        blank=True,
                        to="governanceplatform.sector",
                        verbose_name="Sectors",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company User",
                "verbose_name_plural": "Company Users",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "company"), name="unique_CompanyUser"
                    )
                ],
            },
        ),
    ]
