# Generated by Django 5.1.2 on 2024-11-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("governanceplatform", "0032_alter_observer_functionalities"),
    ]

    operations = [
        migrations.AlterField(
            model_name="functionality",
            name="type",
            field=models.CharField(
                choices=[
                    ("securityobjectives", "Security Objective"),
                    ("reporting", "Reporting"),
                ],
                max_length=100,
                verbose_name="Type",
            ),
        ),
    ]
