# Generated by Django 5.1.2 on 2024-11-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "governanceplatform",
            "0035_remove_company_sector_contacts_remove_user_sectors_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="functionality",
            name="type",
            field=models.CharField(
                choices=[
                    ("securityobjectives", "Security Objective"),
                    ("reporting", "Reporting"),
                ],
                max_length=100,
                verbose_name="Type",
            ),
        ),
        migrations.DeleteModel(
            name="SectorCompanyContact",
        ),
    ]
