# Generated by Django 5.1.5 on 2025-02-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "governanceplatform",
            "0039_alter_scriptlogentry_options_alter_company_address_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="functionality",
            name="type",
            field=models.CharField(
                choices=[
                    ("securityobjectives", "Security Objective"),
                    ("reporting", "Reporting"),
                ],
                max_length=100,
                verbose_name="Type",
            ),
        ),
    ]
