# Generated by Django 5.1.7 on 2025-04-02 13:11

import uuid
from django.db import migrations, models
from django.db import IntegrityError


def generate_activation_tokens(apps, schema_editor):
    User = apps.get_model("governanceplatform", "User")
    for user in User.objects.filter(activation_token__isnull=True):
        unique_uuid = None
        while not unique_uuid:
            try:
                temp_uuid = uuid.uuid4()
                user.activation_token = temp_uuid
                user.save(update_fields=["activation_token"])
                unique_uuid = temp_uuid
            except IntegrityError:
                pass


class Migration(migrations.Migration):

    dependencies = [
        (
            "governanceplatform",
            "0039_alter_scriptlogentry_options_alter_company_address_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="activation_token",
            field=models.UUIDField(null=True, blank=True, unique=True),  # avoid integrity issue
        ),
        migrations.RunPython(generate_activation_tokens),
        migrations.AlterField(
            model_name="user",
            name="activation_token",
            field=models.UUIDField(default=uuid.uuid4, unique=True, editable=False),
        ),
    ]
