# Generated by Django 5.2 on 2025-04-14 10:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("governanceplatform", "0040_alter_functionality_type"),
        ("governanceplatform", "0040_user_activation_token"),
    ]

    operations = []
