# Generated by Django 5.2 on 2025-05-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("governanceplatform", "0040_user_activation_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="address",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="Address",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="entity_categories",
            field=models.ManyToManyField(
                blank=True,
                to="governanceplatform.entitycategory",
                verbose_name="Entity categories",
            ),
        ),
    ]
