# Generated by Django 5.2.3 on 2025-07-03 14:32

from django.db import migrations, models


def set_approved_true(apps, schema_editor):
    CompanyUser = apps.get_model("governanceplatform", "CompanyUser")
    CompanyUser.objects.exclude(user__groups__name="IncidentUser").distinct().update(
        approved=True
    )


class Migration(migrations.Migration):
    dependencies = [
        ("governanceplatform", "0041_alter_company_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyuser",
            name="approved",
            field=models.BooleanField(default=False, verbose_name="Approved"),
        ),
        migrations.RunPython(set_approved_true),
    ]
