# Generated by Django 5.2.4 on 2025-07-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("governanceplatform", "0042_companyuser_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="observer",
            name="rt_queue",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Queue"
            ),
        ),
        migrations.AddField(
            model_name="observer",
            name="rt_token",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Token"
            ),
        ),
        migrations.AddField(
            model_name="observer",
            name="rt_url",
            field=models.URLField(
                blank=True,
                help_text="e.g., https://rt.exemple.com",
                null=True,
                verbose_name="URL",
            ),
        ),
    ]
