# Generated by Django 5.2.1 on 2025-06-02 09:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("governanceplatform", "0041_alter_company_address_and_more"),
        ("governanceplatform", "0042_alter_company_address_and_more"),
    ]

    operations = []
