# Generated by Django 5.2.3 on 2025-07-08 07:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("governanceplatform", "0042_companyuser_approved"),
        ("governanceplatform", "0043_merge_20250602_1114"),
    ]

    operations = []
