# Generated by Django 5.2.3 on 2025-07-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "governanceplatform",
            "0043_observer_rt_queue_observer_rt_token_observer_rt_url",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="observer",
            name="rt_token",
            field=models.CharField(
                blank=True,
                db_column="rt_token",
                max_length=255,
                null=True,
                verbose_name="Token",
            ),
        ),
        migrations.RenameField(
            model_name="observer",
            old_name="rt_token",
            new_name="_rt_token",
        ),
    ]
