# Generated by Django 5.2.5 on 2025-08-19 10:56

from django.db import migrations, models
import random
import string


def generate_alphanum():
    carac = string.ascii_letters + string.digits
    return random.choice(carac)


def rename_duplicate_names(apps, schema_editor):
    Company = apps.get_model("governanceplatform", "Company")

    for company in Company.objects.all():
        index = 0
        change = False
        while Company.objects.filter(name=company.name).exclude(id=company.id).exists():
            company.name = company.name + str(index)
            change = True
        while Company.objects.filter(identifier=company.identifier).exclude(id=company.id).exists():
            caractere = generate_alphanum()
            company.identifier = company.identifier[:3] + caractere
            change = True
        if change:
            company.save()


class Migration(migrations.Migration):
    dependencies = [
        ("governanceplatform", "0044_alter_observer_rt_token_and_more"),
    ]

    operations = [
        migrations.RunPython(rename_duplicate_names),
        migrations.AlterField(
            model_name="company",
            name="identifier",
            field=models.CharField(max_length=4, unique=True, verbose_name="Acronym"),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=64, unique=True, verbose_name="Name"),
        ),
    ]
