# Generated by Django 5.2.5 on 2025-08-13 08:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("governanceplatform", "0044_alter_observer_rt_token_and_more"),
        ("governanceplatform", "0044_merge_20250708_0942"),
    ]

    operations = []
