# Generated by Django 5.2.5 on 2025-08-28 11:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("governanceplatform", "0045_alter_company_identifier_alter_company_name"),
        ("governanceplatform", "0045_merge_20250813_1034"),
    ]

    operations = []
