# Generated by Django 5.2.6 on 2025-09-17 07:11

from django.db import migrations, models


def create_cookiebanner_config(apps, schema_editor):
    ApplicationConfig = apps.get_model("governanceplatform", "ApplicationConfig")

    ApplicationConfig.objects.create(
        key="cookiebanner",
        value=0,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("governanceplatform", "0045_alter_company_identifier_alter_company_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=128, unique=True)),
                ("value", models.CharField(max_length=255)),
            ],
        ),
        migrations.RunPython(create_cookiebanner_config),
    ]
