# Generated by Django 5.2.6 on 2025-09-24 09:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("governanceplatform", "0046_applicationconfig"),
        ("governanceplatform", "0046_merge_20250828_1343"),
    ]

    operations = []
