# Generated by Django 5.2.6 on 2025-10-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governanceplatform", "0046_applicationconfig"),
    ]

    operations = [
        migrations.AlterField(
            model_name="functionality",
            name="type",
            field=models.CharField(
                choices=[("securityobjectives", "Security objective")],
                max_length=100,
                unique=True,
                verbose_name="Type",
            ),
        ),
    ]
