# Generated by Django 5.2.7 on 2025-10-27 12:29

from django.db import migrations, models


def set_email_verified(apps, schema_editor):
    User = apps.get_model("governanceplatform", "User")
    Group = apps.get_model("auth", "Group")

    try:
        incident_group = Group.objects.get(name="IncidentUser")
    except Group.DoesNotExist:
        incident_group = None

    if incident_group:
        User.objects.filter(last_login__isnull=True, groups=incident_group).update(
            email_verified=False
        )


class Migration(migrations.Migration):

    dependencies = [
        ("governanceplatform", "0047_alter_functionality_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="activation_token",
        ),
        migrations.AddField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(
                default=True,
                help_text="Indicates whether the user has verified their email address.",
                verbose_name="Email verified",
            ),
        ),
        migrations.RunPython(set_email_verified),
    ]
