# Generated by Django 5.2.7 on 2025-10-06 12:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("governanceplatform", "0047_alter_functionality_type"),
        (
            "governanceplatform",
            "0047_merge_0046_applicationconfig_0046_merge_20250828_1343",
        ),
    ]

    operations = []
