# Generated by Django 5.2.7 on 2025-10-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governanceplatform", "0048_remove_user_activation_token_user_email_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="observeruser",
            name="can_export_incidents",
            field=models.BooleanField(
                default=False, verbose_name="Can export incidents"
            ),
        ),
        migrations.AddField(
            model_name="regulatoruser",
            name="can_export_incidents",
            field=models.BooleanField(
                default=False, verbose_name="Can export incidents"
            ),
        ),
    ]
