# Generated by Django 5.2.7 on 2025-10-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governanceplatform", "0048_merge_20251006_1450"),
    ]

    operations = [
        migrations.AlterField(
            model_name="functionality",
            name="type",
            field=models.CharField(
                choices=[
                    ("securityobjectives", "Security Objective"),
                    ("reporting", "Reporting"),
                ],
                max_length=100,
                unique=True,
                verbose_name="Type",
            ),
        ),
    ]
