# Generated by Django 5.2.8 on 2025-11-10 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("governanceplatform", "0050_alter_functionality_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companyuser",
            name="sectors",
        ),
    ]
