# Generated by Django 5.2.7 on 2025-11-05 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("governanceplatform", "0049_alter_functionality_type"),
        ("governanceplatform", "0050_alter_functionality_type"),
    ]

    operations = []
