# Generated by Django 5.2.7 on 2025-11-05 10:59

from django.db import migrations, models

import governanceplatform.globals


class Migration(migrations.Migration):

    dependencies = [
        ("governanceplatform", "0051_merge_20251105_1157"),
    ]

    operations = [
        migrations.AlterField(
            model_name="functionality",
            name="type",
            field=models.CharField(
                choices=governanceplatform.globals.get_functionality_choices,
                max_length=100,
                unique=True,
                verbose_name="Type",
            ),
        ),
    ]
