# Generated by Django 5.2.8 on 2025-11-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governanceplatform", "0051_remove_companyuser_sectors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="identifier",
            field=models.CharField(max_length=10, unique=True, verbose_name="Acronym"),
        ),
    ]
