# Generated by Django 5.2.8 on 2025-11-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governanceplatform", "0052_alter_company_identifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether the user has verified their email address.",
                verbose_name="Email verified",
            ),
        ),
    ]
