# Generated by Django 5.2.8 on 2025-11-12 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("governanceplatform", "0051_remove_companyuser_sectors"),
        ("governanceplatform", "0052_alter_functionality_type"),
    ]

    operations = []
