# Generated by Django 5.2.8 on 2025-11-25 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("governanceplatform", "0053_alter_user_email_verified"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="regulation",
            options={
                "verbose_name": "Regulation",
                "verbose_name_plural": "Regulations",
            },
        ),
        migrations.AlterModelOptions(
            name="regulationtranslation",
            options={
                "default_permissions": (),
                "managed": True,
                "verbose_name": "Regulation Translation",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": (
                    ("import_user", "Can import user"),
                    ("export_user", "Can export user"),
                ),
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
    ]
