# Generated by Django 5.2.8 on 2025-11-24 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("governanceplatform", "0052_alter_company_identifier"),
        ("governanceplatform", "0053_merge_20251112_1346"),
    ]

    operations = []
