# Generated by Django 5.2.8 on 2025-11-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governanceplatform", "0054_alter_regulation_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SettingsDummy",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Django Settings",
                "verbose_name_plural": "Django Settings",
                "managed": False,
            },
        ),
    ]
