# Generated by Django 5.2.8 on 2025-11-24 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("governanceplatform", "0053_alter_user_email_verified"),
        ("governanceplatform", "0054_merge_20251124_0920"),
    ]

    operations = []
