# Generated by Django 5.2.11 on 2026-02-13 13:16

import django.core.validators
from django.db import migrations, models

import governanceplatform.validators


class Migration(migrations.Migration):

    dependencies = [
        ("governanceplatform", "0055_settingsdummy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observer",
            name="rt_url",
            field=models.URLField(
                blank=True,
                help_text="e.g., https://rt.exemple.com",
                null=True,
                validators=[
                    django.core.validators.URLValidator(),
                    governanceplatform.validators.validate_rt_url,
                ],
                verbose_name="URL",
            ),
        ),
    ]
