# Generated by Django 5.2.11 on 2026-02-18 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governanceplatform", "0056_alter_observer_rt_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sectortranslation",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="sectortranslation",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="sectortranslation",
            name="language_code",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="sectortranslation",
            name="master",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="governanceplatform.sector",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sectortranslation",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="sectortranslation",
            unique_together={("master", "language_code")},
        ),
        migrations.AlterModelTable(
            name="sectortranslation",
            table=None,
        ),
    ]
