# Generated by Django 5.2.11 on 2026-03-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governanceplatform", "0056_alter_observer_rt_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="sectors",
            field=models.ManyToManyField(
                blank=True, to="governanceplatform.sector", verbose_name="sectors"
            ),
        ),
    ]
