# Generated by Django 6.0.4 on 2026-04-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "governanceplatform",
            "0059_alter_company_country_alter_observer_country_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="entitycategorytranslation",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="functionalitytranslation",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="observertranslation",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="operatortypetranslation",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="regulationtranslation",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="regulatortranslation",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="sectortranslation",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="servicetranslation",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="entitycategorytranslation",
            constraint=models.UniqueConstraint(
                fields=("language_code", "master"),
                name="governanceplatform_entitycategory_translation_uniq_lang",
            ),
        ),
        migrations.AddConstraint(
            model_name="functionalitytranslation",
            constraint=models.UniqueConstraint(
                fields=("language_code", "master"),
                name="governanceplatform_functionality_translation_uniq_lang",
            ),
        ),
        migrations.AddConstraint(
            model_name="observertranslation",
            constraint=models.UniqueConstraint(
                fields=("language_code", "master"),
                name="governanceplatform_observer_translation_uniq_lang",
            ),
        ),
        migrations.AddConstraint(
            model_name="operatortypetranslation",
            constraint=models.UniqueConstraint(
                fields=("language_code", "master"),
                name="governanceplatform_operatortype_translation_uniq_lang",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulationtranslation",
            constraint=models.UniqueConstraint(
                fields=("language_code", "master"),
                name="governanceplatform_regulation_translation_uniq_lang",
            ),
        ),
        migrations.AddConstraint(
            model_name="regulatortranslation",
            constraint=models.UniqueConstraint(
                fields=("language_code", "master"),
                name="governanceplatform_regulator_translation_uniq_lang",
            ),
        ),
        migrations.AddConstraint(
            model_name="sectortranslation",
            constraint=models.UniqueConstraint(
                fields=("language_code", "master"),
                name="governanceplatform_sector_translation_uniq_lang",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicetranslation",
            constraint=models.UniqueConstraint(
                fields=("language_code", "master"),
                name="governanceplatform_service_translation_uniq_lang",
            ),
        ),
    ]
