# data for SO
# standard
standard = [
    {
        "id": "1",
        "label": "ENISA",
        "description": "ENISA",
        "regulator": {"id": 1},
        "regulation": {"id": 1},
    }
]

# domain
domains = [
    {
        "position": 1,
        "label": "D1: Governance and risk management",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "position": 2,
        "label": "D2: Human resources security",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "position": 3,
        "label": "D3: Security of systems and facilities",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "position": 4,
        "label": "D4: Operations management",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "position": 5,
        "label": "D5: Incident management",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "position": 6,
        "label": "D6: Business continuity management",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "position": 7,
        "label": "D7: Monitoring, auditing and testing",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "position": 8,
        "label": "D8: Threat awareness",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
]

# maturity level
levels = [
    {
        "id": "1",
        "level": 0,
        "label": "Sophistication level 0 (N/A)",
        "color": "#e31212",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "id": "2",
        "level": 1,
        "label": "Sophistication level 1 (basic)",
        "color": "#e31212",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "id": "3",
        "level": 2,
        "label": "Sophistication level 2 (industry standard)",
        "color": "#e31212",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "id": "4",
        "level": 3,
        "label": "Sophistication level 3 (state of the art)",
        "color": "#e31212",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
]

# security objectives
sos = [
    {
        "objective": "Information security policy",
        "description": "Establish and maintain an appropriate information security policy",
        "unique_code": "SO1",
        "position": 1,
        "domain": {"position": 1},
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "objective": "Governance and risk management",
        "description": """Establish and maintain an appropriate governance and risk management framework, to identify and address risks for
            the communications networks and services.""",
        "unique_code": "SO2",
        "position": 2,
        "domain": {"position": 1},
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "objective": "Security roles and responsibilities",
        "description": "Establish and maintain an appropriate structure of security roles and responsibilities.",
        "unique_code": "SO3",
        "position": 3,
        "domain": {"position": 1},
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "objective": "Security of third-party dependencies",
        "description": """Establish and maintain a policy, with security requirements for contracts with third parties, to ensure that
            dependencies on third parties do not negatively affect security of networks and/or services.""",
        "unique_code": "SO4",
        "position": 4,
        "domain": {"position": 1},
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "objective": "Background checks",
        "description": "Perform appropriate background checks on personnel if required for their duties and responsibilities.",
        "unique_code": "SO5",
        "position": 5,
        "domain": {"position": 2},
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "objective": "Security knowledge and training",
        "description": "Ensure that personnel have sufficient security knowledge and  they are provided with regular security training.",
        "unique_code": "SO6",
        "position": 6,
        "domain": {"position": 2},
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "objective": "Personnel changes",
        "description": "Establish and maintain an appropriate process for managing changes in personnel or changes in their roles.",
        "unique_code": "SO7",
        "position": 7,
        "domain": {"position": 2},
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "objective": "Handling violations",
        "description": """Establish and maintain a disciplinary process for personnel who violate security policies and have a broader
            process that covers security incidents caused by violations by personnel.""",
        "unique_code": "SO8",
        "position": 8,
        "domain": {"position": 2},
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "objective": "Physical and environmental security",
        "description": "Establish and maintain the appropriate physical and environmental security of network and information systems and "
        "facilities.",
        "unique_code": "SO9",
        "position": 9,
        "domain": {"position": 3},
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "objective": "Security of supplies",
        "description": "Establish and maintain appropriate security of critical supplies (for example electric power, fuel, cooling etc.).",
        "unique_code": "SO10",
        "position": 10,
        "domain": {"position": 3},
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "objective": "Access control to network and information systems",
        "description": "Establish and maintain appropriate (logical) access controls for access to network and information systems.",
        "unique_code": "SO11",
        "position": 11,
        "domain": {"position": 3},
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "objective": "Integrity of network and information systems",
        "description": "Establish and maintain integrity of network and information systems and protect from viruses, code injections, and "
        "other malware that can alter the functionality of systems.",
        "unique_code": "SO12",
        "position": 12,
        "domain": {"position": 3},
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "objective": "Use of encryption",
        "description": "Ensure adequate use of encryption to prevent and/or minimise the impact of security incidents on users and on "
        "other networks and services.",
        "unique_code": "SO13",
        "position": 13,
        "domain": {"position": 3},
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "objective": "Protection of security critical data",
        "description": "Ensure that cryptographic key material and secret authentication information are adequately protected.",
        "unique_code": "SO14",
        "position": 14,
        "domain": {"position": 3},
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "objective": "Operational procedures",
        "description": "Establish and maintain operational procedures for the operation of critical network and information systems by "
        "personnel.",
        "unique_code": "SO15",
        "position": 15,
        "domain": {"position": 4},
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "objective": "Change management",
        "description": "Establish change management procedures for critical network and information systems in order to minimise the "
        "likelihood of incidents resulting from changes.",
        "unique_code": "SO16",
        "position": 16,
        "domain": {"position": 4},
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "objective": "Asset management",
        "description": "Establish and maintain asset management procedures and configuration controls in order to manage availability of "
        "critical assets and configurations of critical network and information systems.",
        "unique_code": "SO17",
        "position": 17,
        "domain": {"position": 4},
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "objective": "Incident management procedures",
        "description": "Establish and maintain procedures for managing incidents, and forwarding them to the appropriate personnel "
        "(triage).",
        "unique_code": "SO18",
        "position": 18,
        "domain": {"position": 5},
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "objective": "Incident detection capability",
        "description": "Establish and maintain an incident detection capability that detects incidents.",
        "unique_code": "SO19",
        "position": 19,
        "domain": {"position": 5},
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "objective": "Incident reporting and communication",
        "description": "Establish and maintain appropriate incident reporting and communication procedures, taking into account national "
        "legislation on incident reporting to government authorities.",
        "unique_code": "SO20",
        "position": 20,
        "domain": {"position": 5},
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "objective": "Service continuity strategy and contingency plans",
        "description": "Establish and maintain contingency plans and a strategy for ensuring continuity of networks and communication "
        "services provided.",
        "unique_code": "SO21",
        "position": 21,
        "domain": {"position": 6},
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "objective": "Disaster recovery capabilities",
        "description": "Establish and maintain an appropriate disaster recovery capability for restoring network and communication "
        "services in case of natural and/or major disasters.",
        "unique_code": "SO22",
        "position": 22,
        "domain": {"position": 6},
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "objective": "Monitoring and logging policies",
        "description": "Establish and maintain systems and functions for monitoring and logging of relevant security events in critical "
        "network and communication systems.",
        "unique_code": "SO23",
        "position": 23,
        "domain": {"position": 7},
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "objective": "Exercise contingency plans",
        "description": "Establish and maintain policies for testing and exercising backup and contingency plans, where needed in "
        "collaboration with third parties.",
        "unique_code": "SO24",
        "position": 24,
        "domain": {"position": 7},
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "objective": "Network and information systems testing",
        "description": "Establish and maintain policies for testing network and information systems, particularly when connecting to new "
        "networks or systems.",
        "unique_code": "SO25",
        "position": 25,
        "domain": {"position": 7},
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "objective": "Security assessments",
        "description": "Establish and maintain an appropriate policy for performing security assessments of network and information "
        "systems.",
        "unique_code": "SO26",
        "position": 26,
        "domain": {"position": 7},
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "objective": "Compliance monitoring",
        "description": "Establish and maintain a policy for monitoring compliance to standards and legal requirements.",
        "unique_code": "SO27",
        "position": 27,
        "domain": {"position": 7},
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "objective": "Threat intelligence",
        "description": "Establish and maintain appropriate mechanisms for monitoring and collecting information about relevant threats to "
        "the security of networks and services.",
        "unique_code": "SO28",
        "position": 28,
        "domain": {"position": 8},
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "objective": "Informing users about threats",
        "description": "Inform users of particular and significant security threats to network or service that may affect the end-user and "
        "of the measures they can take to protect the security of their communications.",
        "unique_code": "SO29",
        "position": 29,
        "domain": {"position": 8},
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
]

# security measures
sms = [
    {
        "security_objective": {"pk": 1},
        "maturity_level": {"id": 4},
        "position": 7,
        "description": "f) Review the information security policies periodically, and take into account violations, exceptions, past "
        "incidents, past tests/exercises, and incidents affecting other (similar) providers in the sector.",
        "evidence": "vi. Information security policies are up to date and approved by senior management.\nvii. Logs of policy exceptions, "
        "approved by the relevant roles.\nviii. Documentation of review process, taking into account changes and past "
        "incidents.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 1},
        "maturity_level": {"id": 3},
        "position": 6,
        "description": "e) Review the security policy following incidents.",
        "evidence": "v. Review comments or change logs for the policy.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 1},
        "maturity_level": {"id": 3},
        "position": 5,
        "description": "d) Make all personnel aware of the security policy and what it implies for their work.",
        "evidence": "iv. Personnel are aware of the information security policy and what it implies for their work (interview).",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 1},
        "maturity_level": {"id": 3},
        "position": 4,
        "description": "c) Set detailed information security policies for critical assets and business processes.",
        "evidence": "iii. Documented information security policies, approved by management, including applicable law and regulations, "
        "accessible to personnel.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 1},
        "maturity_level": {"id": 2},
        "position": 3,
        "description": "b) Make key personnel aware of the security policy.",
        "evidence": "ii. Key personnel are aware of the security policy and its objectives (interview).",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 1},
        "maturity_level": {"id": 2},
        "position": 2,
        "description": "a) Set a high level security policy addressing the security of networks and services.",
        "evidence": "i. Documented security policy, including networks and services in scope, critical assets supporting them, and the "
        "security objectives.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 1},
        "maturity_level": {"id": 1},
        "position": 1,
        "description": "No information security policy available",
        "evidence": "",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 2},
        "maturity_level": {"id": 4},
        "position": 8,
        "description": "g) Review the risk management methodology and/or tools, periodically, taking into account changes and past "
        "incidents.",
        "evidence": "viii. Documentation of the review process and updates of the risk management methodology and/or tools.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 2},
        "maturity_level": {"id": 3},
        "position": 7,
        "description": "f) Ensure residual risks are accepted by management.",
        "evidence": "vii. Management approval of residual risks.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 2},
        "maturity_level": {"id": 3},
        "position": 6,
        "description": "e) Review the risk assessments following changes or incidents.",
        "evidence": "v. List of risks and evidence of updates/reviews.\nvi. Review comments or change logs for risk assessments.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 2},
        "maturity_level": {"id": 3},
        "position": 5,
        "description": "d) Ensure that key personnel use the risk management methodology and tools.",
        "evidence": "iv. Guidance for personnel on assessing risks.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 2},
        "maturity_level": {"id": 3},
        "position": 4,
        "description": "c) Set up a risk management methodology and/or tools based on industry standards.",
        "evidence": "iii. Documented risk management methodology and/or tools.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 2},
        "maturity_level": {"id": 2},
        "position": 3,
        "description": "b) Make key personnel aware of the main risks and how they are mitigated.",
        "evidence": "ii. Key personnel know the main risks (interview).",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 2},
        "maturity_level": {"id": 2},
        "position": 2,
        "description": "a) Make a list of the main risks for security of networks and services, taking into account main threats for the "
        "critical assets.",
        "evidence": "i. List of main risks described at a high level, including the underlying threat(s) and their potential impact on the "
        "security of networks and services",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 2},
        "maturity_level": {"id": 1},
        "position": 1,
        "description": "No governance and risk management framework available",
        "evidence": "",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 3},
        "maturity_level": {"id": 4},
        "position": 6,
        "description": "e) Structure of security roles and responsibilities is regularly reviewed and revised, based on changes and/or "
        "past incidents.",
        "evidence": "iv. Up-to-date documentation of the structure of security role assignments and responsibilities\nv. Documentation of "
        "review process, taking into account changes and past incidents.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 3},
        "maturity_level": {"id": 3},
        "position": 5,
        "description": "d) Make personnel aware of the security roles in your organisation and when they should be contacted.",
        "evidence": "iii. Awareness/dissemination material for personnel explaining security roles and when/how they should be contacted.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 3},
        "maturity_level": {"id": 3},
        "position": 4,
        "description": "c) Personnel is formally appointed in security roles.",
        "evidence": "ii. List of appointments (CISO, DPO, etc.), and description of responsibilities and tasks for security roles (CISO, "
        "DPO, etc.).",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 3},
        "maturity_level": {"id": 2},
        "position": 3,
        "description": "b) Make sure the security roles are reachable in case of security incidents.",
        "evidence": "i. List of security roles (CISO, DPO, business continuity manager, etc.), who occupies them and contact information.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 3},
        "maturity_level": {"id": 2},
        "position": 2,
        "description": "a) Assign security roles and responsibilities to personnel.",
        "evidence": "i. List of security roles (CISO, DPO, business continuity manager, etc.), who occupies them and contact information.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 3},
        "maturity_level": {"id": 1},
        "position": 1,
        "description": "No structure of security roles and responsibility.",
        "evidence": "",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 4},
        "maturity_level": {"id": 4},
        "position": 9,
        "description": "h) Periodically review and update security policy for third parties at regular intervals, taking into account past "
        "incidents, changes, etc.",
        "evidence": "ix. Documentation of the policy review process.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 4},
        "maturity_level": {"id": 4},
        "position": 8,
        "description": "g) Keep track of security incidents related to or caused by third-parties.",
        "evidence": "viii. List of security incidents related to or caused by engagement with third-parties.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 4},
        "maturity_level": {"id": 3},
        "position": 7,
        "description": "f) Mitigate residual risks that are not addressed by the third party.",
        "evidence": "vii. Residual risks resulting from dependencies on third parties are listed and mitigated.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 4},
        "maturity_level": {"id": 3},
        "position": 6,
        "description": "e) Demand specific security standards in third-party supplier's processes during procurement.",
        "evidence": "vi. Contracts with equipment suppliers contain requirements for adhering to security best practices and industry "
        "standards.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 4},
        "maturity_level": {"id": 3},
        "position": 5,
        "description": "d) Review security policy for third parties, following incidents or changes.",
        "evidence": "v. Review comments or change logs of the policy.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 4},
        "maturity_level": {"id": 3},
        "position": 4,
        "description": "c) Ensure that all procurement of services/products from third-parties follows the policy.",
        "evidence": "iv. Contracts for third party services contain security requirements, in line with the security policy for "
        "procurement.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 4},
        "maturity_level": {"id": 3},
        "position": 3,
        "description": "b) Set a security policy for contracts with third-parties.",
        "evidence": "ii. Documented security policy for contracts with third parties.\niii. List of contracts with third-parties.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 4},
        "maturity_level": {"id": 2},
        "position": 2,
        "description": "a) Include security requirements in contracts with third-parties, including confidentiality and secure transfer of "
        "information.",
        "evidence": "i. Explicit security requirements in the contracts with third parties supplying IT products, IT services, outsourced "
        "business processes, helpdesks, call centres, interconnections, shared facilities, etc",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 4},
        "maturity_level": {"id": 1},
        "position": 1,
        "description": "No policy with security requirements for contracts with third parties",
        "evidence": "",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 5},
        "maturity_level": {"id": 4},
        "position": 5,
        "description": "d) Review and update policy/procedures for background checks and reference checks at regular intervals, taking "
        "into account changes and past incidents.",
        "evidence": "iv. Review comments or change logs of the policy/procedures.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 5},
        "maturity_level": {"id": 3},
        "position": 4,
        "description": "c) Set up a policy and procedure for background checks",
        "evidence": "iii. Guidance for personnel about when/how to perform background checks/screenings.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 5},
        "maturity_level": {"id": 3},
        "position": 3,
        "description": "b) Perform background checks/screening for key personnel, when needed and legally permitted.",
        "evidence": "ii. Policy and procedure for background checks/screenings.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 5},
        "maturity_level": {"id": 2},
        "position": 2,
        "description": "a) Check professional references of key personnel (system administrators, security officers, guards, etc.).",
        "evidence": "i. Documentation of checks of professional references for key personnel.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 5},
        "maturity_level": {"id": 1},
        "position": 1,
        "description": "No background checks on personnel",
        "evidence": "",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 6},
        "maturity_level": {"id": 4},
        "position": 6,
        "description": "e) Test the security knowledge of personnel.",
        "evidence": "v. Results of tests of the security knowledge of personnel.\nvi. Review comments or change logs for the program.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 6},
        "maturity_level": {"id": 4},
        "position": 5,
        "description": "d) Review and update the training program periodically, taking into account changes and past incidents.",
        "evidence": "iv. Updated security awareness and training program",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 6},
        "maturity_level": {"id": 3},
        "position": 4,
        "description": "c) Organise trainings and awareness sessions for personnel on security topics important for your organisation.",
        "evidence": "iii. Documented program for training on security skills, including objectives for different roles and how to reach "
        "them (by e.g. training, awareness raising, etc.).",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 6},
        "maturity_level": {"id": 3},
        "position": 3,
        "description": "b) Implement a program for training, making sure that key personnel have sufficient and up-to-date security "
        "knowledge.",
        "evidence": "ii. Personnel have participated in awareness sessions on security topics.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 6},
        "maturity_level": {"id": 2},
        "position": 2,
        "description": "a) Provide key personnel with relevant training and material on security issues.",
        "evidence": "i. Key personnel have followed security trainings and have sufficient security knowledge (interview).",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 6},
        "maturity_level": {"id": 1},
        "position": 1,
        "description": "Personnel with unsufficient security knowledge",
        "evidence": "",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 7},
        "maturity_level": {"id": 4},
        "position": 7,
        "description": "f) Review and evaluate policy/procedures for personnel changes, taking into account changes or past incidents.",
        "evidence": "vi. Up to date policy/procedures for managing personnel changes.\nvii. Review comments or change logs.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 7},
        "maturity_level": {"id": 4},
        "position": 6,
        "description": "e) Periodically check that the policy/procedures are effective.",
        "evidence": "v. Evidence of checks of access rights etc.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 7},
        "maturity_level": {"id": 3},
        "position": 5,
        "description": "d) Implement policy/procedures for education and training for personnel in new roles.",
        "evidence": "iv. Evidence that personnel changes have been carried out according to the process and that access rights have been "
        "updated timely (e.g. checklists).",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 7},
        "maturity_level": {"id": 3},
        "position": 4,
        "description": "c) Implement policy/procedures for personnel changes, taking into account timely revocation of access rights, "
        "badges and equipment.",
        "evidence": "iii. Documentation of process for personnel changes, including responsibilities for managing changes, description of "
        "rights of access and possession of assets per role, procedures for briefing and training personnel in new roles.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 7},
        "maturity_level": {"id": 2},
        "position": 3,
        "description": "b) Brief and educate new personnel on the policies and procedures in place.",
        "evidence": "ii. Evidence that new personnel has been briefed and educated about policies and procedures in place.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 7},
        "maturity_level": {"id": 2},
        "position": 2,
        "description": "a) Following changes in personnel revoke access rights, badges, equipment, etc., if no longer necessary or "
        "permitted.",
        "evidence": "i. Evidence that personnel changes have been followed up with revocation of access rights, badges, equipment, etc.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 7},
        "maturity_level": {"id": 1},
        "position": 1,
        "description": "No process for managing changes in personnel or changes in their roles and responsibilities",
        "evidence": "",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 8},
        "maturity_level": {"id": 4},
        "position": 4,
        "description": "c) Periodically review and update the disciplinary process, based on changes and past incidents.",
        "evidence": "iii. Review comments or change logs",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 8},
        "maturity_level": {"id": 3},
        "position": 3,
        "description": "b) Set up procedures for violations of policies by personnel.",
        "evidence": "ii. Documentation of procedures, including types of violations which may be subject to disciplinary actions, and "
        "which disciplinary actions may be taken.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 8},
        "maturity_level": {"id": 2},
        "position": 2,
        "description": "a) Hold personnel accountable for security incidents caused by violations of policies, for example via the "
        "employment contract.",
        "evidence": "i. Rules for personnel, including responsibilities, code of conduct, violations of policies, etc., possibly as part "
        "of employment contracts.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 8},
        "maturity_level": {"id": 1},
        "position": 1,
        "description": "No disciplinary process for personnel who violate security policies or no process that covers security incidents "
        "caused by violations by personnel",
        "evidence": "",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 9},
        "maturity_level": {"id": 4},
        "position": 7,
        "description": "f) Review and update the policy for physical security measures and environmental controls taking into account "
        "changes and past incidents.",
        "evidence": "vi. Documentation about evaluation of environmental control, review comments or change logs.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 9},
        "maturity_level": {"id": 4},
        "position": 6,
        "description": "e) Evaluate the effectiveness of physical and environmental controls periodically.",
        "evidence": "v. Up to date policy for physical security measures and environmental controls",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 9},
        "maturity_level": {"id": 3},
        "position": 5,
        "description": "d) Apply reinforced controls for physical access to critical assets.",
        "evidence": "iv. The policy includes lists of critical assets and reinforced physical controls for accessing these assets.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 9},
        "maturity_level": {"id": 3},
        "position": 4,
        "description": "c) Industry standard implementation of physical and environmental controls.",
        "evidence": "iii. Physical and environmental controls, like electronic control of entrance and audit trail, segmentation of spaces "
        "according to authorization levels, automated fire extinguishers with halocarbon gases, etc.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 9},
        "maturity_level": {"id": 3},
        "position": 3,
        "description": "b) Implement a policy for physical security measures and environmental controls.",
        "evidence": "ii. Documented policy for physical security measures and environmental controls, including description of facilities "
        "and systems in scope.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 9},
        "maturity_level": {"id": 2},
        "position": 2,
        "description": "a) Prevent unauthorized physical access to facilities and infrastructure and set up adequate environmental "
        "controls, to protect provider assets against unauthorized access, burglary, fire, flooding, etc.",
        "evidence": "i. Basic implementation of physical security measures and environmental controls, such as door and cabinet locks, "
        "burglar alarm, fire alarms, fire extinguishers, etc.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 9},
        "maturity_level": {"id": 1},
        "position": 1,
        "description": "No physical and environmental security of network and information systems and facilities",
        "evidence": "",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 10},
        "maturity_level": {"id": 4},
        "position": 6,
        "description": "e) Review and update policy and procedures to secure critical supplies regularly, taking into account changes and "
        "past incidents.",
        "evidence": "v. Updated policy for securing critical supplies and supporting facilities, review comments and/or change logs.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 10},
        "maturity_level": {"id": 4},
        "position": 5,
        "description": "d) Implement state of the art security measures to protect critical supplies (such as active cooling, UP, hot "
        "standby power generators, SLAs with fuel delivery companies, redundant cooling and power backup systems).",
        "evidence": "iv. Evidence of state of the art measures to protect security of critical supplies.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 10},
        "maturity_level": {"id": 3},
        "position": 4,
        "description": "c) Implement industry standard security measures to protect critical supplies and supporting facilities (e.g. "
        "passive cooling, automatic restart after power interruption, battery backup power, diesel generators, backup "
        "fuel, etc.).",
        "evidence": "iii. Evidence of industry standard measures to protect the security of critical supplies",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 10},
        "maturity_level": {"id": 3},
        "position": 3,
        "description": "b) Implement a policy for security of critical supplies.",
        "evidence": "ii. Documented policy to protect critical supplies such as electrical power, fuel, etc., describing different types "
        "of supplies, and the security measures protecting the supplies.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 10},
        "maturity_level": {"id": 2},
        "position": 2,
        "description": "a) Ensure security of critical supplies.",
        "evidence": "i. Security of critical supplies is protected in a basic way, for example, backup power and/or backup fuel is "
        "available.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 10},
        "maturity_level": {"id": 1},
        "position": 1,
        "description": "No security of critical supplies (for example electric power, fuel, cooling etc.)",
        "evidence": "",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 11},
        "maturity_level": {"id": 4},
        "position": 9,
        "description": "h) Access control policy and access control mechanisms are reviewed and when needed revised.",
        "evidence": "xi. Updates of access control policy, review comments or change logs.\nxii. Documented risk analysis for the "
        "application of logging and retention\nxiii. Procedures to ensure that access controls are in effect all the time and "
        "that they evolve with the network.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 11},
        "maturity_level": {"id": 4},
        "position": 8,
        "description": "g) Evaluate the effectiveness of access control policies and procedures and implement cross checks on access "
        "control mechanisms.",
        "evidence": "viii. Reports of (security) tests of access control mechanisms.\nix. Tools for detection of anomalous usage of "
        "systems or anomalous behaviour of systems (such as intrusion detection and anomaly detection systems).\nx. Logs of "
        "intrusion detection and anomaly detection systems.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 11},
        "maturity_level": {"id": 3},
        "position": 7,
        "description": "f) Reinforce controls for remote access to critical assets of network and information systems by third parties.",
        "evidence": "vi. Principles of least privilege and segregation of duties are documented and applied where appropriate.\nvii. "
        "Remote access to critical assets by third-parties is minimised and subjected to strict access controls, including "
        "state of the art authentication, authorization and auditing controls, especially for privileged accounts.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 11},
        "maturity_level": {"id": 3},
        "position": 6,
        "description": "e) Monitor access to network and information systems, have a process for approving exceptions and registering "
        "access violations.",
        "evidence": "v. Log of access control policy violations and exceptions, approved by the security officer.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 11},
        "maturity_level": {"id": 3},
        "position": 5,
        "description": "d) Choose appropriate authentication mechanisms, depending on the type of access.",
        "evidence": "iv. Different types of authentication mechanisms for different types of access.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 11},
        "maturity_level": {"id": 3},
        "position": 4,
        "description": "c) Implement policy for protecting access to network and information systems, addressing for example roles, "
        "rights, responsibilities and procedures for assigning and revoking access rights.",
        "evidence": "iii. Access control policy including description of roles, groups, access rights, procedures for granting and "
        "revoking access.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 11},
        "maturity_level": {"id": 3},
        "position": 3,
        "description": "b) Implement logical access control mechanism for network and information systems to allow only authorized use.",
        "evidence": "ii. Overview of authentication and access control methods for systems and users.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 11},
        "maturity_level": {"id": 2},
        "position": 2,
        "description": "a) Users and systems have unique ID's and are authenticated before accessing services or systems.",
        "evidence": "i. Access logs show unique identifiers for users and systems when granted or denied access.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 11},
        "maturity_level": {"id": 1},
        "position": 1,
        "description": "No access controls to network or information systems",
        "evidence": "",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 12},
        "maturity_level": {"id": 4},
        "position": 7,
        "description": "f) Evaluate and review the effectiveness of measures to protect integrity of systems.",
        "evidence": "viii. Documentation of process for checking logs of anomaly and intrusion detection systems.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 12},
        "maturity_level": {"id": 4},
        "position": 6,
        "description": "e) Set up state of the art controls to protect integrity of systems.",
        "evidence": "vii. State of the art controls to protect integrity of systems, such as code signing, tripwire, etc.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 12},
        "maturity_level": {"id": 3},
        "position": 5,
        "description": "d) Apply reinforced software integrity, update and patch management controls for critical assets in virtualised "
        "networks.",
        "evidence": "v. Logs of intrusion detection and anomaly detection systems.\nvi. Adequate tools and processes to ensure software "
        "integrity when performing software updates and applying security patches to critical assets in virtualised networks.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 12},
        "maturity_level": {"id": 3},
        "position": 4,
        "description": "c) Implement industry standard security measures, providing defence-in-depth against tampering and altering of "
        "systems.",
        "evidence": "iii. Documentation about how the protection of software and data in network and information system is "
        "implemented.\niv. Tools for detection of anomalous usage of systems or anomalous behaviour of systems (such as "
        "intrusion detection and anomaly detection systems).",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 12},
        "maturity_level": {"id": 2},
        "position": 3,
        "description": "b) Check for malware on (internal) network and information systems.",
        "evidence": "ii. Malware detection systems are present, and up to date.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 12},
        "maturity_level": {"id": 2},
        "position": 2,
        "description": "a) Make sure software of network and information systems is not tampered with or altered, for instance by using "
        "input controls and firewalls.",
        "evidence": "i. Software and data in network and information systems is protected using input controls, firewalls, encryption and "
        "signing.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 12},
        "maturity_level": {"id": 1},
        "position": 1,
        "description": "No integrity of network or information systems, no protection from viruses, code injections, or other malware that "
        "can alter the functionality of systems.",
        "evidence": "",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 13},
        "maturity_level": {"id": 4},
        "position": 6,
        "description": "e) Use state of the art encryption algorithms.",
        "evidence": "vi. Encryption policy includes details about the state of the art cryptographic protocols used.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 13},
        "maturity_level": {"id": 4},
        "position": 5,
        "description": "d) Review and update the encryption policy.",
        "evidence": "v. Updated encryption policy, review comments and/or change logs.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 13},
        "maturity_level": {"id": 3},
        "position": 4,
        "description": "c) Use industry standard encryption algorithms and the corresponding recommended lengths of encryption keys.",
        "evidence": "iv. Documented justified exclusions that provide rationale for when data is not encrypted, including the related "
        "impact assessment.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 13},
        "maturity_level": {"id": 3},
        "position": 3,
        "description": "b) Implement encryption policy.",
        "evidence": "iii. Documented encryption policy including details about the cryptographic algorithms and corresponding "
        "cryptographic keys, according to international best practices and standards.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 13},
        "maturity_level": {"id": 2},
        "position": 2,
        "description": "a) Where appropriate to prevent and/or minimise the impact of security incidents on users and on other networks "
        "and services, encrypt data during its storage in and/or transmission via networks.",
        "evidence": "i. Description of main data flows, and the encryption protocols and algorithms used for each flow.\nii. Description "
        "of justified exclusions and limitations in implementing encryption.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 13},
        "maturity_level": {"id": 1},
        "position": 1,
        "description": "No use of encryption to prevent and/or minimise the impact of security incidents on users and on other networks "
        "and services.",
        "evidence": "",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 14},
        "maturity_level": {"id": 4},
        "position": 7,
        "description": "f) Review and update of user password management policy.",
        "evidence": "vi. Updated user password management policy, review comments and/or change logs.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 14},
        "maturity_level": {"id": 4},
        "position": 6,
        "description": "e) Review and update of key management policy.",
        "evidence": "v. Updated key management policy, review comments and/or change logs.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 14},
        "maturity_level": {"id": 3},
        "position": 5,
        "description": "d) Implement policy for management of user passwords.",
        "evidence": "iv. User password management policy including processes, methods and techniques for secure storing of user passwords "
        "using industry best practices.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 14},
        "maturity_level": {"id": 3},
        "position": 4,
        "description": "c) Implement policy for management of cryptographic keys.",
        "evidence": "iii. Key management policy including roles, responsibilities and controls for the use, protection and lifetime of "
        "cryptographic keys throughout their life cycle including controls for access to and backup and recovery of private "
        "keys.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 14},
        "maturity_level": {"id": 2},
        "position": 3,
        "description": "b) Access to private keys is strictly controlled and monitored.",
        "evidence": "ii. Description of mechanisms for controlling and monitoring access to private keys.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 14},
        "maturity_level": {"id": 2},
        "position": 2,
        "description": "a) Make sure that cryptographic key material and secret authentication information (including cryptographic key "
        "material used for authentication) are not disclosed or tampered with.",
        "evidence": "i. Cryptographic key material and secret authentication information are protected using security best practices and "
        "standards for protection mechanisms (like split knowledge and dual control, encryption, hashing, secure hardware "
        "etc.).",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 14},
        "maturity_level": {"id": 1},
        "position": 1,
        "description": "No protection of cryptographic key material and secret authentication information",
        "evidence": "",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 15},
        "maturity_level": {"id": 4},
        "position": 4,
        "description": "c) Review and update the policy/procedures for operation of critical systems, taking into account incidents and/or "
        "changes.",
        "evidence": "iii. Updated policy/procedures for critical systems, review comments and/or change logs.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 15},
        "maturity_level": {"id": 3},
        "position": 3,
        "description": "b) Implement a policy for operation of systems to make sure all critical systems are operated and managed in line "
        "with predefined procedures.",
        "evidence": "ii. Documented policy for operation of critical systems, including an overview of network and information systems in "
        "scope.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 15},
        "maturity_level": {"id": 2},
        "position": 2,
        "description": "a) Set up operational procedures and assign responsibilities for operation of critical systems.",
        "evidence": "i. Documentation of operational procedures and responsibilities for key network and information systems.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 15},
        "maturity_level": {"id": 1},
        "position": 1,
        "description": "No operational procedures for the operation of critical network and information systems by personnel",
        "evidence": "",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 16},
        "maturity_level": {"id": 4},
        "position": 5,
        "description": "d) Review and update change management procedures regularly, taking into account changes and past incidents.",
        "evidence": "iv. Up to date change management procedures, review comments and/or change logs.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 16},
        "maturity_level": {"id": 3},
        "position": 4,
        "description": "c) Document change management procedures, and record for each change the steps of the followed procedure.",
        "evidence": "iii. For each change, a report is available describing the steps and the result of the change.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 16},
        "maturity_level": {"id": 3},
        "position": 3,
        "description": "b) Implement policy/procedures for change management, to make sure that changes of critical systems are always "
        "done following a predefined way.",
        "evidence": "ii. Documentation of change management policy/procedures, including systems subject to the policy, objectives, roll "
        "back procedures, etc.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 16},
        "maturity_level": {"id": 2},
        "position": 2,
        "description": "a) Follow predefined methods or procedures when making changes to critical systems",
        "evidence": "i. Documentation describing predefined methods or procedures followed when making changes to critical systems.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 16},
        "maturity_level": {"id": 1},
        "position": 1,
        "description": "No change management procedures for critical network and information systems in order to minimise the likelihood "
        "of incidents resulting from changes.",
        "evidence": "",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 17},
        "maturity_level": {"id": 4},
        "position": 4,
        "description": "c) Review and update the asset management policy regularly, based on changes and past incidents.",
        "evidence": "v. Up to date asset management policy/procedures, review comments and/or change logs.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 17},
        "maturity_level": {"id": 3},
        "position": 3,
        "description": "b) Implement policy/procedures for asset management and configuration control.",
        "evidence": "ii. Documented policy/procedures for asset management, including roles and responsibilities, the assets and "
        "configurations that are subject to the policy, the objectives of asset management.\niii. An asset inventory or "
        "inventories, containing critical assets and the dependency between assets.\niv. A configuration control inventory or "
        "inventories, containing configurations of critical systems.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 17},
        "maturity_level": {"id": 2},
        "position": 2,
        "description": "a) Identify critical assets and configurations of critical systems.",
        "evidence": "i. List of critical assets and critical systems. The list should include all critical assets and critical systems for "
        "network or service, operational and security, including relevant third party assets.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 17},
        "maturity_level": {"id": 1},
        "position": 1,
        "description": "No asset management procedures or configuration controls in order to manage availability of critical assets and "
        "configurations of critical network and information systems",
        "evidence": "",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 18},
        "maturity_level": {"id": 4},
        "position": 6,
        "description": "e) Evaluate incident management policy/procedures based on past incidents.",
        "evidence": "v. Up to date incident management policy/procedures, review comments and/or change logs.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 18},
        "maturity_level": {"id": 4},
        "position": 5,
        "description": "d) Investigate major incidents and draft final incident reports, including actions taken and recommendations to "
        "mitigate future occurrence of this type of incident.",
        "evidence": "iv. Individual reports of the handling of major incidents.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 18},
        "maturity_level": {"id": 3},
        "position": 4,
        "description": "c) Implement policy/procedures for managing incidents.",
        "evidence": "iii. Policy/procedures for incident management, including, types of incidents that could occur, objectives, roles and "
        "responsibilities, detailed description, per incident type, how to manage the incident, when to escalate to senior "
        "management (e.g. CISO) etc.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 18},
        "maturity_level": {"id": 2},
        "position": 3,
        "description": "b) Keep a record of all major incidents.",
        "evidence": "ii. Inventory of major incidents per incident, impact, cause, actions taken and lessons learnt.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 18},
        "maturity_level": {"id": 2},
        "position": 2,
        "description": "a) Make sure personnel is available and prepared to manage and handle incidents.",
        "evidence": "i. Personnel is aware of how to deal with incidents and when to escalate.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 18},
        "maturity_level": {"id": 1},
        "position": 1,
        "description": "No procedures for managing incidents, and forwarding them to the appropriate personnel (triage)",
        "evidence": "",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 19},
        "maturity_level": {"id": 4},
        "position": 6,
        "description": "e) Implement state of the art systems and procedures for incident detection.",
        "evidence": "v. Documentation of review of the incident detection process, review comments, and/or change logs.\nvi. NOC/SOC "
        "solutions with state of the art capabilities are used - e.g. SOAR (Security Orchestration, Automation and Response), "
        "ensuring integration with threat and vulnerability management and incident response function, security operations "
        "automation etc.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 19},
        "maturity_level": {"id": 4},
        "position": 5,
        "description": "d) Review systems and processes for incident detection regularly and update them taking into account changes and "
        "past incidents.",
        "evidence": "iv. Up to date documentation of incident detection systems and processes.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 19},
        "maturity_level": {"id": 3},
        "position": 4,
        "description": "c) Implement systems and procedures for registering and forwarding incidents timely to the appropriate people.",
        "evidence": "iii. Network Operation Centres (NOC) and/or Security Operation Centres (SOC) for ensuring visibility and effective "
        "network monitoring and to detect anomalies and to identify and avoid threats.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 19},
        "maturity_level": {"id": 3},
        "position": 3,
        "description": "b) Implement industry standard systems and procedures for incident detection.",
        "evidence": "ii. Incident detection systems and procedures, such as Security Incident and Event Management (SIEM) tools, security "
        "helpdesk for personnel, reports and advisories from Computer Emergency Response Teams (CERTs), tools to spot "
        "anomalies, etc.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 19},
        "maturity_level": {"id": 2},
        "position": 2,
        "description": "a) Set up processes or systems for incident detection.",
        "evidence": "i. Documented examples of past incidents that were detected and timely forwarded to the appropriate people.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 19},
        "maturity_level": {"id": 1},
        "position": 1,
        "description": "No incident detection capability that detects incidents",
        "evidence": "",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 20},
        "maturity_level": {"id": 4},
        "position": 5,
        "description": "d) Review and update the reporting and communication plans, based on changes or past incidents.",
        "evidence": "v. Up to date incident response and communication policy, review comments, and/or change logs.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 20},
        "maturity_level": {"id": 4},
        "position": 4,
        "description": "c) Evaluate past communications and reporting about incidents.",
        "evidence": "iv. List of incident reports and past communications about incidents.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 20},
        "maturity_level": {"id": 3},
        "position": 3,
        "description": "b) Implement policy and procedures for communicating and reporting about incidents.",
        "evidence": "ii. Documented policy and procedures for communicating and reporting about incidents, describing reasons/motivations "
        "for communicating or reporting (business reasons, legal reasons etc.), the type of incidents in scope, the required "
        "content of communications, notifications or reports, the channels to be used, and the roles responsible for "
        "communicating, notifying and reporting.\niii. Templates for incident reporting and communication.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 20},
        "maturity_level": {"id": 2},
        "position": 2,
        "description": "a) Communicate and report about ongoing or past incidents to third parties, customers, and/or government "
        "authorities, when necessary.",
        "evidence": "i. Evidence of past communications and incident reporting.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 20},
        "maturity_level": {"id": 1},
        "position": 1,
        "description": "No appropriate incident reporting and communication procedures, taking into account national legislation on "
        "incident reporting to government authorities",
        "evidence": "",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 21},
        "maturity_level": {"id": 4},
        "position": 7,
        "description": "f) Review and revise contingency plans, based on past incidents and changes.",
        "evidence": "vi. Up to date continuity strategy and contingency plans, review comments, and/or change logs.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 21},
        "maturity_level": {"id": 4},
        "position": 6,
        "description": "e) Review and revise service continuity strategy periodically.",
        "evidence": "v. Map of critical sectors and services essential for and/or dependent on the continuity of the network and service "
        "operation and contingency plans for mitigating the impact related to dependent and interdependent sectors and "
        "services.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 21},
        "maturity_level": {"id": 3},
        "position": 5,
        "description": "d) Implement contingency plans for dependent and inter-dependent critical sectors and services.",
        "evidence": "iv. Logs of activation and execution of contingency plans, including decisions taken, steps followed, final recovery "
        "time.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 21},
        "maturity_level": {"id": 3},
        "position": 4,
        "description": "c) Monitor activation and execution of contingency plans, registering successful and failed recovery times.",
        "evidence": "iii. Decision process for activating contingency plans.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 21},
        "maturity_level": {"id": 3},
        "position": 3,
        "description": "b) Implement contingency plans for critical systems.",
        "evidence": "ii. Contingency plans for critical systems, including clear steps and procedures for common threats, triggers for "
        "activation, steps and recovery time objectives.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 21},
        "maturity_level": {"id": 2},
        "position": 2,
        "description": "a) Implement a service continuity strategy for the communications networks and/or services provided.",
        "evidence": "i. Documented service continuity strategy, including recovery time objectives for key services and processes",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 21},
        "maturity_level": {"id": 1},
        "position": 1,
        "description": "No contingency plans and a strategy for ensuring continuity of networks and communication services provided",
        "evidence": "",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 22},
        "maturity_level": {"id": 4},
        "position": 6,
        "description": "e) Review and update disaster recovery capabilities regularly, taking into account changes, past incidents, and "
        "results of tests and exercises.",
        "evidence": "v. Updated documentation of disaster recovery capabilities in place, review comments and/or change logs.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 22},
        "maturity_level": {"id": 4},
        "position": 5,
        "description": "d) Set up state of the art disaster recovery capabilities to mitigate natural and/major disasters.",
        "evidence": "iv. State of the art disaster recovery capabilities, such as full redundancy and failover mechanisms to handle "
        "natural and/or major disasters.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 22},
        "maturity_level": {"id": 3},
        "position": 4,
        "description": "c) Implement industry standard disaster recovery capabilities, or be assured they are available from third parties "
        "(such as national emergency networks).",
        "evidence": "iii. Industry standard implementation of disaster capabilities, such as mobile equipment, mobile sites, failover "
        "sites, etc.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 22},
        "maturity_level": {"id": 3},
        "position": 3,
        "description": "b) Implement policy/procedures for deploying disaster recovery capabilities.",
        "evidence": "ii. Documented policy/procedures for deploying disaster recovery capabilities, including list of natural and/or major "
        "disasters that could affect the services, and a list of disaster recovery capabilities (either those available "
        "internally or provided by third parties).",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 22},
        "maturity_level": {"id": 2},
        "position": 2,
        "description": "a) Prepare for recovery and restoration of services following disasters.",
        "evidence": "i. Measures are in place for dealing with disasters, such as failover sites in other regions, backups of critical "
        "data to remote locations, etc.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 22},
        "maturity_level": {"id": 1},
        "position": 1,
        "description": "No disaster recovery capability for restoring network and communication services in case of natural and/or major "
        "disasters",
        "evidence": "",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 23},
        "maturity_level": {"id": 4},
        "position": 7,
        "description": "f) Review and update logging and monitoring policy/procedures, taking into account changes and past incidents.",
        "evidence": "vi. Updated documentation of monitoring and logging policy/procedures, review comments, and/or change logs.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 23},
        "maturity_level": {"id": 4},
        "position": 6,
        "description": "e) Set up tools for automated collection and analysis of monitoring data and logs.",
        "evidence": "v. Tools to facilitate structural recording and analysis of monitoring and logs.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 23},
        "maturity_level": {"id": 3},
        "position": 5,
        "description": "d) Set up tools to collect and store logs of critical systems.",
        "evidence": "iv. List of monitoring data and log files, in line with the policy.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 23},
        "maturity_level": {"id": 3},
        "position": 4,
        "description": "c) Set up tools for monitoring critical systems",
        "evidence": "iii. Tools for monitoring systems and collecting logs.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 23},
        "maturity_level": {"id": 3},
        "position": 3,
        "description": "b) Implement policy for logging and monitoring of critical systems.",
        "evidence": "ii. Documented policy for monitoring and logging, including minimum monitoring and logging requirements, retention "
        "period, and the overall objectives of storing monitoring data and logs.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 23},
        "maturity_level": {"id": 2},
        "position": 2,
        "description": "a) Implement monitoring and logging of critical systems.",
        "evidence": "i. Logs and monitoring reports of critical network and information systems.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 23},
        "maturity_level": {"id": 1},
        "position": 1,
        "description": "No systems and functions for monitoring and logging of relevant security events in critical network and "
        "communication systems.",
        "evidence": "",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 24},
        "maturity_level": {"id": 4},
        "position": 6,
        "description": "e) Involve suppliers and other third parties in exercises, for example business partners and customers.",
        "evidence": "vi. Input from suppliers and other third parties involved about how to improve exercise scenarios.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 24},
        "maturity_level": {"id": 4},
        "position": 5,
        "description": "d) Review and update the exercise plans, taking into account changes, past incidents and contingencies which were "
        "not covered by the exercise program.",
        "evidence": "v. Updated exercise plans, review comments, and/or change logs.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 24},
        "maturity_level": {"id": 3},
        "position": 4,
        "description": "c) Make sure that the issues and lessons learnt from exercises are addressed by the responsible people and that "
        "the relevant processes and systems are updated accordingly.",
        "evidence": "iii. Reports about exercises and drills showing the execution of contingency plans, including lessons learnt from the "
        "exercises.\niv. Issues and lessons learnt from past exercises have been addressed by the responsible people.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 24},
        "maturity_level": {"id": 3},
        "position": 3,
        "description": "b) Implement a program for exercising backup and contingency plans regularly, using realistic scenarios covering a "
        "range of different scenarios over time.",
        "evidence": "ii. Exercise program for backup and contingency plans, including types of contingencies, frequency, roles and "
        "responsibilities, templates and procedures for conducting exercises, templates for exercise reports.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 24},
        "maturity_level": {"id": 2},
        "position": 2,
        "description": "a) Exercise and test backup and contingency plans to make sure systems and processes work and personnel is "
        "prepared for large failures and contingencies.",
        "evidence": "i. Reports of past exercises of backup and contingency plans.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 24},
        "maturity_level": {"id": 1},
        "position": 1,
        "description": "No policies for testing and exercising backup and contingency plans, where needed in collaboration with third "
        "parties",
        "evidence": "",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 25},
        "maturity_level": {"id": 4},
        "position": 5,
        "description": "d) Review and update the policy/procedures for testing, taking into account changes and past incidents.",
        "evidence": "iv. Updated policy/procedures for testing networks and information systems, review comments, and/or change log.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 25},
        "maturity_level": {"id": 3},
        "position": 4,
        "description": "c) Implement tools for automated testing",
        "evidence": "iii. List of test reports.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 25},
        "maturity_level": {"id": 3},
        "position": 3,
        "description": "b) Implement policy/procedures for testing network and information systems.",
        "evidence": "ii. Policy/procedures for testing networks and information systems, including when tests must be carried out, test "
        "plans, test cases, test report templates.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 25},
        "maturity_level": {"id": 2},
        "position": 2,
        "description": "a) Test networks and information systems before using them or connecting them to existing systems.",
        "evidence": "i. Test reports of the network and information systems, including tests after big changes or the introduction of new "
        "systems.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 25},
        "maturity_level": {"id": 1},
        "position": 1,
        "description": "No policies for testing network and information systems, particularly when connecting to new networks or systems",
        "evidence": "",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 26},
        "maturity_level": {"id": 4},
        "position": 5,
        "description": "d) Review and update policy/procedures for security assessments and security testing, taking into account changes "
        "and past incidents.",
        "evidence": "v. Up to date policy/procedures for security assessments and security testing, review comments, and/or change log.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 26},
        "maturity_level": {"id": 4},
        "position": 4,
        "description": "c) Evaluate the effectiveness of policy/procedures for security assessments and security testing.",
        "evidence": "iii. List of reports about security assessments and security tests.\niv. Reports of follow up actions on assessments "
        "and test results.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 26},
        "maturity_level": {"id": 3},
        "position": 3,
        "description": "b) Implement policy/procedures for security assessments and security testing.",
        "evidence": "ii. Documented policy/procedures for security assessments and security testing, including, which assets, in what "
        "circumstances, the type of security assessments and tests, frequency, approved parties (internal or external), "
        "confidentiality levels for assessment, test results and the objectives of security assessments and tests.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 26},
        "maturity_level": {"id": 2},
        "position": 2,
        "description": "a) Ensure critical systems undergo security scans and security testing regularly, particularly when new systems "
        "are introduced and following changes.",
        "evidence": "i. Reports from past security scans and security tests.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 26},
        "maturity_level": {"id": 1},
        "position": 1,
        "description": "No policy for performing security assessments of network and information systems",
        "evidence": "",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 27},
        "maturity_level": {"id": 4},
        "position": 5,
        "description": "d) Review and update the policy/procedures for compliance and auditing, taking into account changes and past "
        "incidents.",
        "evidence": "v. Updated policy/procedures for compliance and auditing, review comments, and/or change logs.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 27},
        "maturity_level": {"id": 4},
        "position": 4,
        "description": "c) Evaluate the policy/procedures for compliance and auditing.",
        "evidence": "iv. List of all compliance and audit reports",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 27},
        "maturity_level": {"id": 3},
        "position": 3,
        "description": "b) Implement policy/procedures for compliance monitoring and auditing.",
        "evidence": "ii. Documented policy/procedures for monitoring compliance and auditing, including what (assets, processes, "
        "infrastructure), frequency, guidelines who should carry out audits (in- or external), relevant security policies "
        "that are subject to compliance monitoring and auditing, the objectives and high level approach of compliance "
        "monitoring and auditing, templates for audit reports.\niii. Detailed monitoring and audit plans, including long term "
        "high level objectives and planning",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 27},
        "maturity_level": {"id": 2},
        "position": 2,
        "description": "a) Monitor compliance to standards and legal requirements.",
        "evidence": "i. Reports describing the result of compliance monitoring.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 27},
        "maturity_level": {"id": 1},
        "position": 1,
        "description": "No policy for monitoring compliance to standards and legal requirements.",
        "evidence": "",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 28},
        "maturity_level": {"id": 4},
        "position": 5,
        "description": "d) Threat intelligence program makes use of state of the art threat intelligence systems.",
        "evidence": "vii. Threat intelligence platform (TIP) with state of the art functionality is used (e.g. consolidation of threat "
        "intelligence feeds from various sources, automation, security analytics and integration with other security tools "
        "etc.)",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 28},
        "maturity_level": {"id": 4},
        "position": 4,
        "description": "c) Review and update the threat intelligence program.",
        "evidence": "vi. Updated threat intelligence program, review comments and/or change logs.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 28},
        "maturity_level": {"id": 3},
        "position": 3,
        "description": "b) Implement threat intelligence program.",
        "evidence": "iii. Documented and implemented threat intelligence program that includes roles, responsibilities, procedures and "
        "mechanisms for collecting information related to significant threats and corresponding mitigation measures.\niv. The "
        "program also includes mechanisms for systematic sharing of threat intelligence with relevant organisations on "
        "bilateral and multilateral basis using a dedicated threat intelligence sharing platform (e.g. MISP).\nv. Appropriate "
        "information marking scheme in place for facilitation of sharing of sensitive threat information (e.g. TLP).",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 28},
        "maturity_level": {"id": 2},
        "position": 2,
        "description": "a) Perform regular threat monitoring.",
        "evidence": "i. Regular monitoring of external threat intelligence feeds (OSINT, commercial feeds, security researches etc.) with "
        "a recorded log of relevant significant threat events.\nii. Informal and ad-hoc sharing of relevant threat "
        "intelligence with relevant organisations on bilateral basis.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 28},
        "maturity_level": {"id": 1},
        "position": 1,
        "description": "No mechanisms for monitoring and collecting information about relevant threats to the security of networks and "
        "services",
        "evidence": "",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 29},
        "maturity_level": {"id": 4},
        "position": 4,
        "description": "c) Review and update the policy/procedures for regular update of end-users about security threats to network or "
        "service that may affect them.",
        "evidence": "v. Updated outreach policy, review comments and/or change logs.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 29},
        "maturity_level": {"id": 3},
        "position": 3,
        "description": "b) Implement policy/procedures for regular update of end-users about security threats to network or service that "
        "may affect them.",
        "evidence": "iii. Documented and implemented end-user outreach policy with defined roles and responsibilities, mechanisms and "
        "criteria for identifying significant threats and procedures, tools and methods for timely and appropriate informing "
        "of end-users.\niv. The policy includes mechanisms for identifying and sharing recommendations and best practices for "
        "end-users to mitigate specific threats.",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 29},
        "maturity_level": {"id": 2},
        "position": 2,
        "description": "a) Inform end-users of communication networks and services about particular and significant security threats to "
        "network or service that may affect them.",
        "evidence": "i. Security bulletin, a dedicated threat information web page or another documented and tested mechanism for reaching "
        "out to end-users in case of significant threats.\nii. Documented lists of best practices and security "
        "recommendations for end-users to mitigate typical risks (e.g. encryption, strong authentication, updates, backups, "
        "user awareness etc.).",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
    {
        "security_objective": {"pk": 29},
        "maturity_level": {"id": 1},
        "position": 1,
        "description": "No information to users of particular and significant security threats to network or service that may affect the "
        "end-user and of the measures they can take to protect the security of their communications",
        "evidence": "",
        "creator": {"id": 1},
        "standard": {"id": 1},
    },
]
