# Generated by Django 4.2 on 2023-09-29 09:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="predefinedanswer",
            name="allowed_additional_answer",
        ),
    ]
