# Generated by Django 4.2 on 2023-10-25 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='Reglementation',
            new_name='reglementation',
        ),
    ]
