# Generated by Django 4.2.5 on 2023-10-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0002_remove_predefinedanswer_allowed_additional_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="other_authority",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="questiontranslation",
            name="tooltip",
            field=models.TextField(blank=True, null=True),
        ),
    ]
