# Generated by Django 4.2 on 2023-10-25 12:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0002_rename_reglementation_incident_reglementation"),
    ]

    operations = [
        migrations.CreateModel(
            name="IncidentWorkflow",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("DELIV", "Delivered but not yet reviewed"),
                            ("PASS", "Review passed"),
                            ("FAIL", "Review failed"),
                            ("OUT", "Final notification missing. due date exceeded"),
                        ],
                        default="DELIV",
                        max_length=5,
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="incidents.incident",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="incidents.workflow",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="incident",
            name="workflows",
            field=models.ManyToManyField(
                related_name="incident_workflow",
                through="incidents.IncidentWorkflow",
                to="incidents.workflow",
            ),
        ),
    ]
