# Generated by Django 4.2 on 2023-09-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0002_incident_authorities"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="other_authority",
            field=models.TextField(blank=True, null=True),
        ),
    ]
