# Generated by Django 4.2 on 2023-11-03 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_remove_answer_incident_answer_incident_workflow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_preliminary',
        ),
    ]
