# Generated by Django 4.2 on 2024-04-17 11:46

from django.db import migrations, models
import django.db.models.constraints


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0002_sectorregulation_report_status_changed_email"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="sectorregulationworkflow",
            name="Unique_SectorRegulationWorkflowPosition",
        ),
        migrations.AddConstraint(
            model_name="sectorregulationworkflow",
            constraint=models.UniqueConstraint(
                deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                fields=("sector_regulation", "position"),
                name="Unique_SectorRegulationWorkflowPosition",
            ),
        ),
    ]
