# Generated by Django 4.2 on 2024-07-17 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("governanceplatform", "0003_alter_cert_country_alter_regulator_country"),
        (
            "incidents",
            "0003_remove_sectorregulationworkflow_unique_sectorregulationworkflowposition_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="impact",
            options={"verbose_name": "Impacts", "verbose_name_plural": "Impact"},
        ),
        migrations.AlterModelOptions(
            name="impacttranslation",
            options={
                "default_permissions": (),
                "managed": True,
                "verbose_name": "Impacts Translation",
            },
        ),
        migrations.AlterModelOptions(
            name="question",
            options={"verbose_name": "Questions", "verbose_name_plural": "Question"},
        ),
        migrations.AlterModelOptions(
            name="questiontranslation",
            options={
                "default_permissions": (),
                "managed": True,
                "verbose_name": "Questions Translation",
            },
        ),
        migrations.AlterModelOptions(
            name="sectorregulationworkflow",
            options={
                "verbose_name": "Links between workflorw and report",
                "verbose_name_plural": "Link between workflorw and report",
            },
        ),
        migrations.AlterModelOptions(
            name="workflow",
            options={
                "verbose_name": "Incident report",
                "verbose_name_plural": "Incident reports",
            },
        ),
        migrations.AlterField(
            model_name="answer",
            name="answer",
            field=models.TextField(blank=True, null=True, verbose_name="Answer"),
        ),
        migrations.AlterField(
            model_name="answer",
            name="incident_workflow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="incidents.incidentworkflow",
                verbose_name="Incident report answered",
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="predefined_answers",
            field=models.ManyToManyField(
                blank=True,
                to="incidents.predefinedanswer",
                verbose_name="Predefined answer",
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="incidents.question",
                verbose_name="Question",
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="timestamp",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Timestamp"
            ),
        ),
        migrations.AlterField(
            model_name="email",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="governanceplatform.regulator",
                verbose_name="Creator",
            ),
        ),
        migrations.AlterField(
            model_name="email",
            name="creator_name",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="Creator Name",
            ),
        ),
        migrations.AlterField(
            model_name="email",
            name="name",
            field=models.CharField(
                blank=True, default=None, max_length=255, null=True, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="emailtranslation",
            name="content",
            field=models.TextField(verbose_name="Content"),
        ),
        migrations.AlterField(
            model_name="emailtranslation",
            name="subject",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="Subject",
            ),
        ),
        migrations.AlterField(
            model_name="impact",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="governanceplatform.regulator",
                verbose_name="Creator",
            ),
        ),
        migrations.AlterField(
            model_name="impact",
            name="creator_name",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="Creator name",
            ),
        ),
        migrations.AlterField(
            model_name="impact",
            name="regulation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="governanceplatform.regulation",
                verbose_name="Regulation",
            ),
        ),
        migrations.AlterField(
            model_name="impact",
            name="sectors",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                to="governanceplatform.sector",
                verbose_name="Sectors",
            ),
        ),
        migrations.AlterField(
            model_name="impacttranslation",
            name="headline",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="Headline",
            ),
        ),
        migrations.AlterField(
            model_name="impacttranslation",
            name="label",
            field=models.TextField(verbose_name="Label"),
        ),
        migrations.AlterField(
            model_name="incident",
            name="affected_sectors",
            field=models.ManyToManyField(
                to="governanceplatform.sector", verbose_name="Affected sectors"
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="affected_services",
            field=models.ManyToManyField(
                to="governanceplatform.service", verbose_name="Affected Service"
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="authorities",
            field=models.ManyToManyField(
                related_name="authorities",
                to="governanceplatform.regulator",
                verbose_name="Authorities",
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="company",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="governanceplatform.company",
                verbose_name="Company",
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="complaint_reference",
            field=models.CharField(max_length=255, verbose_name="Complaint reference"),
        ),
        migrations.AlterField(
            model_name="incident",
            name="contact_user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Contact user",
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="impacts",
            field=models.ManyToManyField(
                default=None, to="incidents.impact", verbose_name="Impacts"
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="incident_detection_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Incident detection date"
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="incident_notification_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name="Incident notification date",
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="incident_reference",
            field=models.CharField(max_length=255, verbose_name="Incident reference"),
        ),
        migrations.AlterField(
            model_name="incident",
            name="incident_starting_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Incident starting date"
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="incident_status",
            field=models.CharField(
                choices=[("CLOSE", "Closed"), ("GOING", "On-going")],
                default="GOING",
                max_length=5,
                verbose_name="Incident status",
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("UNDE", "Not delivered"),
                    ("DELIV", "Delivered but not yet reviewed"),
                    ("PASS", "Review passed"),
                    ("FAIL", "Review failed"),
                    ("OUT", "Not delivered and deadline exceeded"),
                ],
                default="UNDE",
                max_length=5,
                verbose_name="Review status",
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="sector_regulation",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="incidents.sectorregulation",
                verbose_name="Workflow",
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="workflows",
            field=models.ManyToManyField(
                through="incidents.IncidentWorkflow",
                to="incidents.workflow",
                verbose_name="Incident reports",
            ),
        ),
        migrations.AlterField(
            model_name="incidentworkflow",
            name="comment",
            field=models.TextField(blank=True, null=True, verbose_name="Comment"),
        ),
        migrations.AlterField(
            model_name="incidentworkflow",
            name="impacts",
            field=models.ManyToManyField(
                default=None, to="incidents.impact", verbose_name="Impacts"
            ),
        ),
        migrations.AlterField(
            model_name="incidentworkflow",
            name="incident",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="incidents.incident",
                verbose_name="Incident",
            ),
        ),
        migrations.AlterField(
            model_name="incidentworkflow",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("UNDE", "Not delivered"),
                    ("DELIV", "Delivered but not yet reviewed"),
                    ("PASS", "Review passed"),
                    ("FAIL", "Review failed"),
                    ("OUT", "Not delivered and deadline exceeded"),
                ],
                default="UNDE",
                max_length=5,
                verbose_name="Review status",
            ),
        ),
        migrations.AlterField(
            model_name="incidentworkflow",
            name="timestamp",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Timestamp"
            ),
        ),
        migrations.AlterField(
            model_name="incidentworkflow",
            name="workflow",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="incidents.workflow",
                verbose_name="Incident report",
            ),
        ),
        migrations.AlterField(
            model_name="predefinedanswer",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="governanceplatform.regulator",
                verbose_name="Creator",
            ),
        ),
        migrations.AlterField(
            model_name="predefinedanswer",
            name="creator_name",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="Creator Name",
            ),
        ),
        migrations.AlterField(
            model_name="predefinedanswer",
            name="position",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="Position"
            ),
        ),
        migrations.AlterField(
            model_name="predefinedanswer",
            name="question",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="incidents.question",
                verbose_name="Question",
            ),
        ),
        migrations.AlterField(
            model_name="predefinedanswertranslation",
            name="predefined_answer",
            field=models.TextField(verbose_name="Answer"),
        ),
        migrations.AlterField(
            model_name="question",
            name="category",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="incidents.questioncategory",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="governanceplatform.regulator",
                verbose_name="Creator",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="creator_name",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="Creator Name",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="position",
            field=models.IntegerField(verbose_name="Position"),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("FREETEXT", "Freetext"),
                    ("MULTI", "Multiple Choice"),
                    ("SO", "Single Option Choice"),
                    ("MT", "Multiple Choice + Free Text"),
                    ("ST", "Single Choice + Free Text"),
                    ("CL", "Country list"),
                    ("RL", "Region list"),
                    ("DATE", "Date picker"),
                ],
                default="FREETEXT",
                max_length=10,
                verbose_name="Question Type",
            ),
        ),
        migrations.AlterField(
            model_name="questioncategory",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="governanceplatform.regulator",
                verbose_name="Creator",
            ),
        ),
        migrations.AlterField(
            model_name="questioncategory",
            name="creator_name",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="Creator name",
            ),
        ),
        migrations.AlterField(
            model_name="questioncategory",
            name="position",
            field=models.IntegerField(verbose_name="Position"),
        ),
        migrations.AlterField(
            model_name="questioncategorytranslation",
            name="label",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="Label",
            ),
        ),
        migrations.AlterField(
            model_name="questiontranslation",
            name="label",
            field=models.TextField(verbose_name="Label"),
        ),
        migrations.AlterField(
            model_name="questiontranslation",
            name="tooltip",
            field=models.TextField(blank=True, null=True, verbose_name="Tooltip"),
        ),
        migrations.AlterField(
            model_name="sectorregulation",
            name="closing_email",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="closing_email",
                to="incidents.email",
                verbose_name="Closing e-mail",
            ),
        ),
        migrations.AlterField(
            model_name="sectorregulation",
            name="opening_email",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="opening_email",
                to="incidents.email",
                verbose_name="Opening e-mail",
            ),
        ),
        migrations.AlterField(
            model_name="sectorregulation",
            name="regulation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="governanceplatform.regulation",
                verbose_name="Regulation",
            ),
        ),
        migrations.AlterField(
            model_name="sectorregulation",
            name="regulator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="governanceplatform.regulator",
                verbose_name="Regulator",
            ),
        ),
        migrations.AlterField(
            model_name="sectorregulation",
            name="report_status_changed_email",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="report_status_changed_email",
                to="incidents.email",
                verbose_name="Email for status change",
            ),
        ),
        migrations.AlterField(
            model_name="sectorregulation",
            name="sectors",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                to="governanceplatform.sector",
                verbose_name="Sectors",
            ),
        ),
        migrations.AlterField(
            model_name="sectorregulation",
            name="workflows",
            field=models.ManyToManyField(
                through="incidents.SectorRegulationWorkflow",
                to="incidents.workflow",
                verbose_name="Incident reports",
            ),
        ),
        migrations.AlterField(
            model_name="sectorregulationtranslation",
            name="name",
            field=models.CharField(
                blank=True, default=None, max_length=255, null=True, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="sectorregulationworkflow",
            name="delay_in_hours_before_deadline",
            field=models.IntegerField(
                default=0, verbose_name="Delay in hours before deadline"
            ),
        ),
        migrations.AlterField(
            model_name="sectorregulationworkflow",
            name="emails",
            field=models.ManyToManyField(
                through="incidents.SectorRegulationWorkflowEmail",
                to="incidents.email",
                verbose_name="E-mails",
            ),
        ),
        migrations.AlterField(
            model_name="sectorregulationworkflow",
            name="position",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="Position"
            ),
        ),
        migrations.AlterField(
            model_name="sectorregulationworkflow",
            name="sector_regulation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="incidents.sectorregulation",
                verbose_name="Workflow",
            ),
        ),
        migrations.AlterField(
            model_name="sectorregulationworkflow",
            name="trigger_event_before_deadline",
            field=models.CharField(
                choices=[
                    ("NONE", "None"),
                    ("NOTIF_DATE", "Notification Date"),
                    ("DETECT_DATE", "Detection Date"),
                    ("PREV_WORK", "Previous Workflow"),
                ],
                default="NONE",
                max_length=15,
                verbose_name="Trigger event before deadline",
            ),
        ),
        migrations.AlterField(
            model_name="sectorregulationworkflow",
            name="workflow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="incidents.workflow",
                verbose_name="Incident report",
            ),
        ),
        migrations.AlterField(
            model_name="sectorregulationworkflowemail",
            name="delay_in_hours",
            field=models.IntegerField(default=0, verbose_name="Delay in hour"),
        ),
        migrations.AlterField(
            model_name="sectorregulationworkflowemail",
            name="email",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="incidents.email",
                verbose_name="E-mail",
            ),
        ),
        migrations.AlterField(
            model_name="sectorregulationworkflowemail",
            name="sector_regulation_workflow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="incidents.sectorregulationworkflow",
                verbose_name="Link between workflorw and report",
            ),
        ),
        migrations.AlterField(
            model_name="sectorregulationworkflowemail",
            name="trigger_event",
            field=models.CharField(
                choices=[
                    ("NOTIF_DATE", "Notification Date of the workflow"),
                    ("PREV_WORK", "Previous Workflow date"),
                ],
                default="NOTIF_DATE",
                max_length=15,
                verbose_name="Trigger event",
            ),
        ),
        migrations.AlterField(
            model_name="sectorregulationworkflowemailtranslation",
            name="headline",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="Headline",
            ),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="governanceplatform.regulator",
                verbose_name="Creator",
            ),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="creator_name",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="Creator Name",
            ),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="questions",
            field=models.ManyToManyField(
                to="incidents.question", verbose_name="Questions"
            ),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="submission_email",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submission_email",
                to="incidents.email",
                verbose_name="Submision e-mail",
            ),
        ),
        migrations.AlterField(
            model_name="workflowtranslation",
            name="name",
            field=models.CharField(
                blank=True, default=None, max_length=255, null=True, verbose_name="Name"
            ),
        ),
    ]
