# Generated by Django 4.2 on 2023-10-25 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_incidentworkflow_incident_workflows'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReglementationWorkflows',
            new_name='ReglementationWorkflow',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='workflows',
        ),
        migrations.RemoveField(
            model_name='incidentworkflow',
            name='workflow',
        ),
        migrations.AddField(
            model_name='incident',
            name='reglementation_workflows',
            field=models.ManyToManyField(through='incidents.IncidentWorkflow', to='incidents.reglementationworkflow'),
        ),
        migrations.AddField(
            model_name='incidentworkflow',
            name='reglementation_workflow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='incidents.reglementationworkflow'),
        ),
    ]
