# Generated by Django 4.2 on 2023-10-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_alter_incident_other_authority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='predefinedanswer',
            name='position',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
