# Generated by Django 4.2.5 on 2023-11-07 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0003_remove_question_is_preliminary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="predefined_answers",
        ),
        migrations.AddField(
            model_name="predefinedanswer",
            name="question",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="incidents.question",
            ),
        ),
    ]
