# Generated by Django 4.2.5 on 2023-09-26 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0004_added_incident_and_review_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="answer",
            old_name="PredefinedAnswer",
            new_name="predefined_answers",
        ),
    ]
