# Generated by Django 4.2 on 2023-10-26 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0004_rename_reglementationworkflows_reglementationworkflow_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='reglementation_workflows',
        ),
        migrations.RemoveField(
            model_name='incidentworkflow',
            name='reglementation_workflow',
        ),
        migrations.AddField(
            model_name='incident',
            name='workflows',
            field=models.ManyToManyField(through='incidents.IncidentWorkflow', to='incidents.workflow'),
        ),
        migrations.AddField(
            model_name='incidentworkflow',
            name='workflow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='incidents.workflow'),
        ),
    ]
