# Generated by Django 4.2 on 2023-11-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0005_incident_affected_sectors"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="incident_detection_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="incident",
            name="incident_starting_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sectorregulation",
            name="is_detection_date_needed",
            field=models.BooleanField(
                default=False, verbose_name="Detection date needed"
            ),
        ),
    ]
