# Generated by Django 5.0.6 on 2024-07-17 10:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0004_incident_incident_timezone"),
        ("incidents", "0005_logreportread"),
    ]

    operations = []
