# Generated by Django 5.0.6 on 2024-07-23 08:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0006_merge_20240717_1240"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="incident_detection_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="incident",
            name="incident_notification_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="incident",
            name="incident_starting_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
