# Generated by Django 4.2 on 2023-11-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0006_incident_incident_detection_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectorregulationworkflow',
            name='emails',
            field=models.ManyToManyField(to='incidents.email'),
        ),
        migrations.AlterField(
            model_name='email',
            name='email_type',
            field=models.CharField(choices=[('CLOSE', 'Incident Closing'), ('OPEN', 'Incident Openning'), ('WDONE', 'Workflow done'), ('REMIND', 'Workflow reminder')], default='CLOSE', max_length=10),
        ),
    ]
