# Generated by Django 4.2 on 2023-11-22 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0006_incident_incident_detection_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="email_type",
            field=models.CharField(
                choices=[
                    ("CLOSE", "Incident Closing"),
                    ("OPEN", "Incident Openning"),
                    ("WDONE", "Workflow done"),
                    ("REMIND", "Workflow reminder"),
                ],
                default="CLOSE",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="SectorRegulationWorkflowEmail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trigger_event",
                    models.CharField(
                        choices=[
                            ("NOTIF_DATE", "Notification Date"),
                            ("DETECT_DATE", "Detection Date"),
                            ("PREV_WORK", "Previous Workflow"),
                        ],
                        default="NOTIF_DATE",
                        max_length=15,
                    ),
                ),
                ("delay_in_hours", models.IntegerField(default=0)),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="incidents.email",
                    ),
                ),
                (
                    "sector_regulation_workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="incidents.sectorregulationworkflow",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="sectorregulationworkflow",
            name="emails",
            field=models.ManyToManyField(
                through="incidents.SectorRegulationWorkflowEmail", to="incidents.email"
            ),
        ),
    ]
