# Generated by Django 4.2.7 on 2023-11-29 10:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0008_remove_email_days_before_send_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="incident_detection_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
