# Generated by Django 5.1 on 2024-09-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0009_alter_incident_incident_timezone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questioncategorytranslation",
            name="label",
            field=models.CharField(
                default="[MISSING_TRANSLATION]", max_length=255, verbose_name="Label"
            ),
            preserve_default=False,
        ),
    ]
