# Generated by Django 4.2 on 2023-11-30 12:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0009_sectorregulation_closing_email_and_more"),
        ("incidents", "0010_alter_incident_incident_detection_date_and_more"),
    ]

    operations = []
