# Generated by Django 4.2 on 2023-12-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0011_merge_20231130_1220"),
    ]

    operations = [
        migrations.AddField(
            model_name="sectorregulationworkflow",
            name="delay_in_hours_before_deadline",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sectorregulationworkflow",
            name="trigger_event_before_deadline",
            field=models.CharField(
                choices=[
                    ("NONE", "None"),
                    ("NOTIF_DATE", "Notification Date"),
                    ("DETECT_DATE", "Detection Date"),
                    ("PREV_WORK", "Previous Workflow"),
                ],
                default="NONE",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("DELIV", "Delivered but not yet reviewed"),
                    ("PASS", "Review passed"),
                    ("FAIL", "Review failed"),
                    ("OUT", "Not delivered and deadline exceeded"),
                ],
                default="DELIV",
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="incidentworkflow",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("DELIV", "Delivered but not yet reviewed"),
                    ("PASS", "Review passed"),
                    ("FAIL", "Review failed"),
                    ("OUT", "Not delivered and deadline exceeded"),
                ],
                default="DELIV",
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="sectorregulationworkflowemail",
            name="trigger_event",
            field=models.CharField(
                choices=[
                    ("NOTIF_DATE", "Notification Date"),
                    ("PREV_WORK", "Previous Workflow"),
                ],
                default="NOTIF_DATE",
                max_length=15,
            ),
        ),
    ]
