# Generated by Django 5.1 on 2024-09-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0012_alter_workflowtranslation_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sectorregulationtranslation",
            name="name",
            field=models.CharField(
                default="[MISSING_TRANSLATION]", max_length=255, verbose_name="Name"
            ),
            preserve_default=False,
        ),
    ]
