# Generated by Django 4.2 on 2023-12-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "incidents",
            "0012_sectorregulationworkflow_delay_in_hours_before_deadline_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="incident_status",
            field=models.CharField(
                choices=[("CLOSE", "Closed"), ("GOING", "On-going")],
                default="GOING",
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="sectorregulationworkflowemail",
            name="trigger_event",
            field=models.CharField(
                choices=[
                    ("NOTIF_DATE", "Notification Date of the workflow"),
                    ("PREV_WORK", "Previous Workflow date"),
                ],
                default="NOTIF_DATE",
                max_length=15,
            ),
        ),
    ]
