# Generated by Django 4.2 on 2023-12-15 10:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0013_alter_incident_incident_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
