# Generated by Django 5.1 on 2024-09-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0013_alter_sectorregulationtranslation_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sectorregulationworkflowemailtranslation",
            name="headline",
            field=models.CharField(
                default="[MISSING_TRANSLATION]", max_length=255, verbose_name="Headline"
            ),
            preserve_default=False,
        ),
    ]
