# Generated by Django 4.2 on 2023-12-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0014_answer_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("UNDE", "Not delivered"),
                    ("DELIV", "Delivered but not yet reviewed"),
                    ("PASS", "Review passed"),
                    ("FAIL", "Review failed"),
                    ("OUT", "Not delivered and deadline exceeded"),
                ],
                default="UNDE",
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="incidentworkflow",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("UNDE", "Not delivered"),
                    ("DELIV", "Delivered but not yet reviewed"),
                    ("PASS", "Review passed"),
                    ("FAIL", "Review failed"),
                    ("OUT", "Not delivered and deadline exceeded"),
                ],
                default="UNDE",
                max_length=5,
            ),
        ),
    ]
