# Generated by Django 5.0.8 on 2024-09-11 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0014_alter_sectorregulationworkflowemailtranslation_headline"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sectorregulationworkflow",
            options={
                "verbose_name": "Links between workflow and report",
                "verbose_name_plural": "Link between workflow and report",
            },
        ),
        migrations.AlterField(
            model_name="sectorregulationworkflowemail",
            name="sector_regulation_workflow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="incidents.sectorregulationworkflow",
                verbose_name="Link between workflow and report",
            ),
        ),
        migrations.CreateModel(
            name="PredefinedAnswerOptions",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.IntegerField(verbose_name="Position")),
                (
                    "predefined_answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="incidents.predefinedanswer",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="answer",
            name="predefined_answer_options",
            field=models.ManyToManyField(
                blank=True,
                to="incidents.predefinedansweroptions",
                verbose_name="Predefined answer options",
            ),
        ),
        migrations.CreateModel(
            name="QuestionCategoryOptions",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.IntegerField(verbose_name="Position")),
                (
                    "question_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="incidents.questioncategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuestionOptions",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(default=False, verbose_name="Mandatory"),
                ),
                ("position", models.IntegerField(verbose_name="Position")),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="incidents.questioncategory",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="incidents.question",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="incidents.workflow",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="predefinedansweroptions",
            name="question_options",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="predefined_answers",
                to="incidents.questionoptions",
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="question_options",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="incidents.questionoptions",
                verbose_name="Question options",
            ),
        ),
    ]
