# Generated by Django 4.2 on 2023-12-20 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("governanceplatform", "0005_remove_company_monarc_path_and_more"),
        ("incidents", "0015_alter_incident_review_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="impact",
            name="is_generic_impact",
        ),
        migrations.RemoveField(
            model_name="sectorregulation",
            name="impacts",
        ),
        migrations.AddField(
            model_name="impact",
            name="regulation",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="governanceplatform.regulation",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="impact",
            name="sectors",
            field=models.ManyToManyField(
                blank=True, default=None, to="governanceplatform.sector"
            ),
        ),
        migrations.AddField(
            model_name="incidentworkflow",
            name="impacts",
            field=models.ManyToManyField(default=None, to="incidents.impact"),
        ),
    ]
