# Generated by Django 4.2 on 2023-12-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0016_remove_impact_is_generic_impact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='is_impact_needed',
            field=models.BooleanField(default=False, verbose_name='Impacts are needed'),
        ),
    ]
