# Generated by Django 4.2 on 2023-12-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0017_workflow_is_impact_needed"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="email",
            options={
                "verbose_name": "Email template",
                "verbose_name_plural": "Email templates",
            },
        ),
        migrations.AlterModelOptions(
            name="emailtranslation",
            options={
                "default_permissions": (),
                "managed": True,
                "verbose_name": "Email template Translation",
            },
        ),
        migrations.AlterModelOptions(
            name="predefinedanswer",
            options={
                "verbose_name": "Question - predefined answer",
                "verbose_name_plural": "Question - predefined answers",
            },
        ),
        migrations.AlterModelOptions(
            name="predefinedanswertranslation",
            options={
                "default_permissions": (),
                "managed": True,
                "verbose_name": "Question - predefined answer Translation",
            },
        ),
        migrations.AlterModelOptions(
            name="sectorregulation",
            options={
                "verbose_name": "Incident notification workflow",
                "verbose_name_plural": "Incident notification workflows",
            },
        ),
        migrations.AlterModelOptions(
            name="sectorregulationtranslation",
            options={
                "default_permissions": (),
                "managed": True,
                "verbose_name": "Incident notification workflow Translation",
            },
        ),
        migrations.AlterModelOptions(
            name="sectorregulationworkflowemail",
            options={
                "verbose_name": "Email for Incident notification workflow",
                "verbose_name_plural": "Emails for Incident notification workflows",
            },
        ),
        migrations.AlterModelOptions(
            name="workflow",
            options={
                "verbose_name": "Incident report",
                "verbose_name_plural": "Incident Reports",
            },
        ),
        migrations.AlterModelOptions(
            name="workflowtranslation",
            options={
                "default_permissions": (),
                "managed": True,
                "verbose_name": "Incident report Translation",
            },
        ),
        migrations.AddField(
            model_name="incidentworkflow",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
