# Generated by Django 5.1.1 on 2024-10-02 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("governanceplatform", "0028_remove_observerregulation_is_spoc"),
        ("incidents", "0017_alter_question_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="regulator",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="governanceplatform.regulator",
                verbose_name="Regulator",
            ),
        ),
    ]
