# Generated by Django 4.2 on 2024-01-10 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "incidents",
            "0018_alter_email_options_alter_emailtranslation_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="workflow",
            name="submission_email",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submission_email",
                to="incidents.email",
            ),
        ),
    ]
