# Generated by Django 4.2 on 2024-01-11 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("governanceplatform", "0005_remove_company_monarc_path_and_more"),
        ("incidents", "0019_workflow_submission_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="creator_id",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="governanceplatform.regulator",
            ),
        ),
        migrations.AddField(
            model_name="email",
            name="creator_name",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
