# Generated by Django 5.1.1 on 2024-10-10 09:07

from django.db import migrations


def transfer_predefined_answer_options(apps, schema_editor):
    PredefinedAnswerOptions = apps.get_model("incidents", "PredefinedAnswerOptions")

    updated_predefined_answers = set()

    for pao in PredefinedAnswerOptions.objects.all():
        predefined_answer = pao.predefined_answer

        if predefined_answer.id not in updated_predefined_answers:
            question_option = pao.question_options
            question = question_option.question

            predefined_answer.question = question
            predefined_answer.position = pao.position
            predefined_answer.save()

            updated_predefined_answers.add(predefined_answer.id)


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0019_predefinedanswer_position_predefinedanswer_question"),
    ]

    operations = [
        migrations.RunPython(transfer_predefined_answer_options),
    ]
