# Generated by Django 4.2 on 2024-01-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0020_email_creator_email_creator_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailtranslation",
            name="headline",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="impacttranslation",
            name="headline",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
