# Generated by Django 5.1.1 on 2024-10-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0020_recovery_predefinedanswer_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="predefined_answers",
            field=models.ManyToManyField(blank=True, to="incidents.predefinedanswer"),
        ),
    ]
