# Generated by Django 4.2 on 2024-02-01 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("governanceplatform", "0006_alter_company_country"),
        ("incidents", "0021_impacttranslation_headline_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="impact",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="governanceplatform.regulator",
            ),
        ),
        migrations.AddField(
            model_name="impact",
            name="creator_name",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="predefinedanswer",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="governanceplatform.regulator",
            ),
        ),
        migrations.AddField(
            model_name="predefinedanswer",
            name="creator_name",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="governanceplatform.regulator",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="creator_name",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="questioncategory",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="governanceplatform.regulator",
            ),
        ),
        migrations.AddField(
            model_name="questioncategory",
            name="creator_name",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="workflow",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="governanceplatform.regulator",
            ),
        ),
        migrations.AddField(
            model_name="workflow",
            name="creator_name",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
