# Generated by Django 5.1.1 on 2024-10-10 11:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0022_transfer_predefined_answers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answer",
            name="predefined_answer_options",
        ),
        migrations.DeleteModel(
            name="PredefinedAnswerOptions",
        ),
    ]
