# Generated by Django 4.2 on 2024-02-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0022_impact_creator_impact_creator_name_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="sectorregulationworkflow",
            constraint=models.UniqueConstraint(
                fields=("sector_regulation", "position"),
                name="Unique_SectorRegulationWorkflowPosition",
            ),
        ),
    ]
