# Generated by Django 5.1.2 on 2024-10-18 09:27

from django.db import migrations
from django.core.exceptions import ObjectDoesNotExist


def populate_question_catgegory_option(apps, schema_editor):
    Report = apps.get_model("incidents", "Workflow")
    QuestionCategoryOptions = apps.get_model("incidents", "QuestionCategoryOptions")
    QuestionOptions = apps.get_model("incidents", "QuestionOptions")
    QuestionCategoryOptions.objects.all().delete()

    for report in Report.objects.all():
        position = 0
        for qo in QuestionOptions.objects.filter(report=report):
            qco = None
            try:
                qco = QuestionCategoryOptions.objects.get(
                    question_category=qo.category,
                    report=report,
                    )
            except ObjectDoesNotExist:
                qco = None
            if qco is not None:
                qo.category_option = qco
            else:
                qco = QuestionCategoryOptions.objects.create(
                    question_category=qo.category,
                    report=report,
                    position=position
                )
                position = position + 10
                qo.category_option = qco

            qo.save()


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0024_alter_questioncategoryoptions_options_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_question_catgegory_option),
    ]
