# Generated by Django 5.1.2 on 2024-10-29 08:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0026_remove_questionoptions_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questioncategoryoptions",
            name="report",
        ),
    ]
