# Generated by Django 5.1.2 on 2024-12-03 15:13

import django.db.models.deletion
from django.db import migrations, models


def set_default_category_option(apps, schema_editor):
    QuestionOptions = apps.get_model("incidents", "QuestionOptions")

    for question_option in QuestionOptions.objects.filter(category_option__isnull=True):
        if question_option.report:
            question_option_by_report = QuestionOptions.objects.filter(
                report=question_option.report,
                category_option__isnull=False,
            )
            if question_option_by_report:
                category_option = question_option_by_report.first().category_option
                question_option.category_option = category_option
                question_option.save()
            else:
                question_option.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0027_remove_questioncategoryoptions_report"),
    ]

    operations = [
        migrations.RunPython(set_default_category_option),
        migrations.AlterField(
            model_name="questionoptions",
            name="category_option",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="incidents.questioncategoryoptions",
            ),
        ),
    ]
