# Generated by Django 5.1.2 on 2024-12-19 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "incidents",
            "0029_alter_email_options_alter_emailtranslation_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="question_options",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="incidents.questionoptions",
                verbose_name="Questionnaire",
            ),
        ),
        migrations.AlterField(
            model_name="impacttranslation",
            name="headline",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="Title",
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="contact_firstname",
            field=models.CharField(max_length=100, verbose_name="Contact first name"),
        ),
        migrations.AlterField(
            model_name="incident",
            name="contact_lastname",
            field=models.CharField(max_length=100, verbose_name="Contact last name"),
        ),
        migrations.AlterField(
            model_name="incident",
            name="contact_telephone",
            field=models.CharField(max_length=100, verbose_name="Contact telephone"),
        ),
        migrations.AlterField(
            model_name="incident",
            name="technical_firstname",
            field=models.CharField(max_length=100, verbose_name="Technical first name"),
        ),
        migrations.AlterField(
            model_name="incident",
            name="technical_lastname",
            field=models.CharField(max_length=100, verbose_name="Technical last name"),
        ),
        migrations.AlterField(
            model_name="incident",
            name="technical_telephone",
            field=models.CharField(max_length=100, verbose_name="Technical telephone"),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="submission_email",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submission_email",
                to="incidents.email",
                verbose_name="Submission email",
            ),
        ),
    ]
