# Generated by Django 5.1.7 on 2025-03-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0030_alter_answer_question_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incidentworkflow",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("UNDE", "Unsubmitted"),
                    ("DELIV", "Under review"),
                    ("PASS", "Passed"),
                    ("FAIL", "Failed"),
                    ("OUT", "Submission overdue"),
                    ("LATE", "Late submission"),
                ],
                default="UNDE",
                max_length=5,
                verbose_name="Report status",
            ),
        ),
    ]
