# Generated by Django 5.1.7 on 2025-04-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0031_alter_incidentworkflow_review_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="logreportread",
            name="entity_name",
            field=models.CharField(
                default="", max_length=250, verbose_name="Entity name"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="logreportread",
            name="role",
            field=models.CharField(default="", max_length=250, verbose_name="Role"),
            preserve_default=False,
        ),
    ]
