# Generated by Django 5.2.1 on 2025-05-08 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governanceplatform", "0041_alter_company_address_and_more"),
        ("incidents", "0032_logreportread_entity_name_logreportread_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="impact",
            name="regulations",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="regulations",
                to="governanceplatform.regulation",
                verbose_name="Legal basis",
            ),
        ),
        migrations.AlterField(
            model_name="impact",
            name="regulation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="regulation",
                to="governanceplatform.regulation",
                verbose_name="Legal basis",
            ),
        ),
    ]
