# Generated by Django 5.2.1 on 2025-05-08 08:00

from django.db import migrations


def migrate_data(apps, schema_editor):
    Impact = apps.get_model("incidents", "Impact")
    for impact in Impact.objects.all():
        impact.regulations.add(impact.regulation)


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0033_impact_regulations_alter_impact_regulation"),
    ]

    operations = [
        migrations.RunPython(migrate_data)
    ]
