# Generated by Django 5.2.1 on 2025-05-08 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0034_migrate_impact_regulations"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="impact",
            name="regulation",
        ),
    ]
