# Generated by Django 5.2.1 on 2025-06-02 08:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0035_remove_impact_regulation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workflow",
            name="questions",
        ),
        migrations.AddField(
            model_name="questionoptions",
            name="is_deleted",
            field=models.BooleanField(default=True, verbose_name="Deleted"),
        ),
        migrations.CreateModel(
            name="QuestionOptionsHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.CharField(max_length=100, verbose_name="Event recorded"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Timestamp"
                    ),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(default=False, verbose_name="Mandatory"),
                ),
                ("position", models.IntegerField(verbose_name="Position")),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="incidents.question",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="questionoptions",
            name="historic",
            field=models.ManyToManyField(
                blank=True, to="incidents.questionoptionshistory"
            ),
        ),
    ]
