# Generated by Django 5.2.1 on 2025-05-27 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0035_remove_impact_regulation"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="WorkflowQuestions",
                    fields=[
                        (
                            "id",
                            models.AutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "question",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="incidents.question",
                                verbose_name="Question",
                            ),
                        ),
                        (
                            "workflow",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="incidents.workflow",
                                verbose_name="Workflow",
                            ),
                        ),
                    ],
                    options={
                        'db_table': 'incidents_workflow_questions',
                    },
                ),
                migrations.AlterField(
                    model_name="workflow",
                    name="questions",
                    field=models.ManyToManyField(
                        through="incidents.WorkflowQuestions",
                        to="incidents.question",
                        verbose_name="Questions",
                    ),
                ),
            ]
        ),
    ]
