# Generated by Django 5.2.1 on 2025-05-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0036_workflowquestions_alter_workflow_questions"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowquestions",
            name="archive_date",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
