# Generated by Django 5.2.1 on 2025-06-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    def set_is_deleted(apps, schema_editor):
        QuestionOptions = apps.get_model("incidents", "QuestionOptions")

        for question_option in QuestionOptions.objects.all():
            question_option.is_deleted = False
            question_option.save()

    dependencies = [
        (
            "incidents",
            "0036_remove_workflow_questions_questionoptions_is_deleted_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(set_is_deleted),
        migrations.AlterField(
            model_name="questionoptions",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Deleted"),
        ),
    ]
