# Generated by Django 5.2.1 on 2025-05-28 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0037_workflowquestions_archive_date_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="workflowquestions",
            table=None,
        ),
    ]
