# Generated by Django 5.2.1 on 2025-06-02 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0037_alter_questionoptions_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionoptionshistory",
            name="category_option",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                to="incidents.questioncategoryoptions",
            ),
        ),
    ]
