# Generated by Django 5.2.1 on 2025-05-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0038_alter_workflowquestions_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowquestions",
            name="added_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
