# Generated by Django 5.2.1 on 2025-06-02 11:54

import datetime
from django.db import migrations, models
from django.utils.timezone import make_aware


class Migration(migrations.Migration):

    def set_created_at(apps, schema_editor):
        default_date = make_aware(datetime.datetime(2000, 1, 1))
        QuestionOptions = apps.get_model("incidents", "QuestionOptions")

        for question_option in QuestionOptions.objects.all():
            question_option.created_at = default_date
            question_option.save()

    dependencies = [
        ("incidents", "0039_question_reference_questionoptions_created_at"),
    ]

    operations = [
        migrations.RunPython(set_created_at),
        migrations.AlterField(
            model_name="questionoptions",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2000, 1, 1, 0, 0), verbose_name="Created at"
            ),
        ),
    ]
