# Generated by Django 5.2.1 on 2025-06-16 05:57

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0039_workflowquestions_added_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workflow",
            name="questions",
        ),
        migrations.AddField(
            model_name="question",
            name="reference",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="Reference",
            ),
        ),
        migrations.AddField(
            model_name="questionoptions",
            name="deleted_date",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="Deleted date"
            ),
        ),
        migrations.AddField(
            model_name="questionoptions",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2000, 1, 1, 0, 0), verbose_name="Updated at"
            ),
        ),
        migrations.CreateModel(
            name="QuestionOptionsHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Timestamp"
                    ),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(default=False, verbose_name="Mandatory"),
                ),
                ("position", models.IntegerField(verbose_name="Position")),
                (
                    "category_option",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="incidents.questioncategoryoptions",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="incidents.question",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="questionoptions",
            name="historic",
            field=models.ManyToManyField(
                blank=True, to="incidents.questionoptionshistory"
            ),
        ),
        migrations.DeleteModel(
            name="WorkflowQuestions",
        ),
    ]
