# Generated by Django 5.2.1 on 2025-06-06 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0040_alter_questionoptions_created_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="questionoptions",
            old_name="created_at",
            new_name="updated_at",
        ),
        migrations.RemoveField(
            model_name="questionoptionshistory",
            name="event",
        ),
    ]
