# Generated by Django 5.2.4 on 2025-07-17 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "governanceplatform",
            "0043_observer_rt_queue_observer_rt_token_observer_rt_url",
        ),
        ("incidents", "0040_remove_workflow_questions_question_reference_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RTTicket",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticket_id", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="incidents.incident",
                    ),
                ),
                (
                    "observer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="governanceplatform.observer",
                    ),
                ),
            ],
        ),
    ]
