# Generated by Django 5.2.5 on 2025-08-12 12:44
from django.db import migrations, models


def migrate_name_from_translations(apps, schema_editor):
    Workflow = apps.get_model("incidents", "Workflow")
    WorkflowTranslation = apps.get_model("incidents", "WorkflowTranslation")

    default_lang = "en"

    for wf in Workflow.objects.all().only("id", "name_temp"):
        translation = WorkflowTranslation.objects.filter(
            master_id=wf.id, language_code=default_lang
        ).first()
        if not translation:
            translation = WorkflowTranslation.objects.filter(master_id=wf.id).first()
        if translation and translation.name:
            wf.name_temp = translation.name.strip()
            wf.save(update_fields=["name_temp"])

    for t in WorkflowTranslation.objects.all():
        if t.name:
            t.label = t.name.strip()
            t.save(update_fields=["label"])


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0041_rtticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflow",
            name="name_temp",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Name"
            ),
        ),
        migrations.AddField(
            model_name="workflowtranslation",
            name="description",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Description"
            ),
        ),
        migrations.AddField(
            model_name="workflowtranslation",
            name="label",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Label"
            ),
        ),
        migrations.RunPython(migrate_name_from_translations),
        migrations.AlterField(
            model_name="workflowtranslation",
            name="label",
            field=models.CharField(max_length=255, verbose_name="Label"),
        ),
    ]
