# Generated by Django 5.2.1 on 2025-06-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0041_rename_created_at_questionoptions_updated_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questionoptions",
            name="is_deleted",
        ),
        migrations.AddField(
            model_name="questionoptions",
            name="deleted_date",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="Deleted date"
            ),
        ),
    ]
