# Generated by Django 5.2.1 on 2025-06-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0042_remove_questionoptions_is_deleted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="reference",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="Reference",
            ),
        ),
    ]
