# Generated by Django 5.2.5 on 2025-08-12 13:37

from collections import defaultdict

from django.db import migrations, models


def rename_duplicate_names(apps, schema_editor):
    Workflow = apps.get_model("incidents", "Workflow")
    WorkflowTranslation = apps.get_model("incidents", "WorkflowTranslation")
    default_lang = "en"
    name_counter = defaultdict(int)

    for wf in Workflow.objects.order_by("id"):
        translation = WorkflowTranslation.objects.filter(
            master_id=wf.id, language_code=default_lang
        ).first()
        if not translation:
            translation = WorkflowTranslation.objects.filter(master_id=wf.id).first()
        if translation and translation.name:
            name_counter[translation.name] += 1
            count = name_counter[translation.name]
            if count > 1:
                wf.name_temp = f"{translation.name} ({count})"
                wf.save(update_fields=["name_temp"])


class Migration(migrations.Migration):
    dependencies = [
        (
            "incidents",
            "0042_workflow_name_temp_workflowtranslation_description_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(rename_duplicate_names),
        migrations.RemoveField(
            model_name="workflowtranslation",
            name="name",
        ),
        migrations.RenameField(
            model_name="workflow",
            old_name="name_temp",
            new_name="name",
        ),
        migrations.AlterField(
            model_name="workflow",
            name="name",
            field=models.CharField(verbose_name="Name", max_length=255, unique=True),
        ),
    ]
