# Generated by Django 5.2.5 on 2025-08-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0043_rename_duplicate_workflow_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("UNDE", "Unsubmitted"),
                    ("DELIV", "Under review"),
                    ("PASS", "Passed"),
                    ("FAIL", "Revision required"),
                    ("OUT", "Submission overdue"),
                ],
                default="UNDE",
                max_length=5,
                verbose_name="Report status",
            ),
        ),
        migrations.AlterField(
            model_name="incidentworkflow",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("UNDE", "Unsubmitted"),
                    ("DELIV", "Under review"),
                    ("PASS", "Passed"),
                    ("FAIL", "Revision required"),
                    ("OUT", "Submission overdue"),
                    ("LATE", "Late submission"),
                ],
                default="UNDE",
                max_length=5,
                verbose_name="Report status",
            ),
        ),
    ]
