# Generated by Django 5.2.5 on 2025-08-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0044_alter_incident_review_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incidentworkflow",
            name="comment",
            field=models.TextField(
                blank=True, null=True, verbose_name="Comment/Explanation"
            ),
        ),
    ]
