# Generated by Django 5.2.5 on 2025-08-25 06:26

from django.db import migrations


def get_latest_incident_workflow(IncidentWorkflow, incident):
    incident_workflow = (
        IncidentWorkflow.objects.filter(
            incident=incident,
        )
        .order_by("-timestamp")
        .first()
    )

    return incident_workflow


def get_incident_workflows(IncidentWorkflow, incident):
    incident_workflows = (
        IncidentWorkflow.objects.filter(
            incident=incident,
        )
        .order_by("-timestamp")
        .distinct()
    )

    return incident_workflows


def migrate_date(apps, schema_editor):
    Incident = apps.get_model("incidents", "Incident")
    ReportTimeline = apps.get_model("incidents", "ReportTimeline")
    IncidentWorkflow = apps.get_model("incidents", "IncidentWorkflow")

    for incident in Incident.objects.all():
        latest_report = get_latest_incident_workflow(IncidentWorkflow, incident)
        for report in get_incident_workflows(IncidentWorkflow, incident):
            if report.id == latest_report.id:
                rt = ReportTimeline.objects.create(
                    report_timeline_timezone=incident.incident_timezone,
                    incident_detection_date=incident.incident_detection_date,
                    incident_starting_date=incident.incident_starting_date,
                    incident_resolution_date=None,
                )
            else:
                rt = ReportTimeline.objects.create(
                    report_timeline_timezone=incident.incident_timezone,
                    incident_detection_date=None,
                    incident_starting_date=None,
                    incident_resolution_date=None,
                )
            latest_report.report_timeline = rt
            latest_report.save()


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0046_reporttimeline_incidentworkflow_report_timeline"),
    ]

    operations = [
        migrations.RunPython(migrate_date),
        migrations.RemoveField(
            model_name="incident",
            name="incident_starting_date",
        ),
    ]
