# Generated by Django 5.2.5 on 2025-09-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0047_remove_incident_incident_detection_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sectorregulationworkflowemail",
            name="trigger_event",
            field=models.CharField(
                choices=[
                    ("NOTIF_DATE", "Notification Date of the workflow"),
                    ("PREV_WORK", "Previous Workflow date"),
                    ("DETEC_DATE", "Incident detection date"),
                ],
                default="NOTIF_DATE",
                max_length=15,
                verbose_name="Trigger event",
            ),
        ),
    ]
