# Generated by Django 5.2.6 on 2025-09-24 06:31

from django.db import migrations, models
import random
import string


def generate_alphanum():
    carac = string.ascii_letters + string.digits
    return random.choice(carac)


def migrate_reference(apps, schema_editor):
    Question = apps.get_model("incidents", "Question")
    questions = Question.objects.all().distinct()

    for q in questions:
        change = False
        while questions.filter(reference=q.reference).exclude(id=q.id).exists() or q.reference is None:
            if q.reference is None:
                q.reference = q.id
                change = True
            else:
                caractere = generate_alphanum()
                q.reference = q.reference + caractere
                change = True
        if change:
            q.save()


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0048_alter_sectorregulationworkflowemail_trigger_event"),
    ]

    operations = [
        migrations.RunPython(migrate_reference),
        migrations.AlterField(
            model_name="question",
            name="reference",
            field=models.CharField(max_length=255, verbose_name="Reference"),
        ),
    ]
