# Generated by Django 5.2.6 on 2025-09-26 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0049_alter_question_reference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionoptions",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    1999, 12, 31, 23, 0, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Updated at",
            ),
        ),
    ]
