# Generated by Django 5.2.6 on 2025-10-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0050_alter_questionoptions_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtranslation",
            name="content",
            field=models.TextField(
                help_text="Available placeholders: #INCIDENT_NOTIFICATION_DATE#,\n                #INCIDENT_DETECTION_DATE#,\n                #INCIDENT_STARTING_DATE#,\n                #INCIDENT_ID#,\n                #DEADLINE#",
                verbose_name="Content",
            ),
        ),
    ]
