# Generated by Django 5.2.6 on 2025-10-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0051_alter_emailtranslation_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logreportread",
            name="action",
            field=models.CharField(max_length=250, verbose_name="Action performed"),
        ),
    ]
