# Generated by Django 5.2.8 on 2025-11-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0052_alter_logreportread_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="incident_id",
            field=models.CharField(max_length=28, verbose_name="Incident ID"),
        ),
    ]
