# Generated by Django 5.2.10 on 2026-01-30 09:16

from django.db import migrations, models


def migrate_last_update(apps, schema_editor):
    Incident = apps.get_model("incidents", "Incident")
    LogReportRead = apps.get_model("incidents", "LogReportRead")

    for inc in Incident.objects.all():
        last_log = (
            LogReportRead.objects.filter(
                incident=inc,
            )
            .exclude(
                action__in=["READ", "DOWNLOAD"],
            )
            .order_by("-timestamp", "-id")
            .first()
        )
        if last_log:
            inc.incident_last_update = last_log.timestamp
            inc.save()


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0053_alter_incident_incident_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="incident_last_update",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(migrate_last_update),
    ]
