# Generated by Django 5.2.10 on 2026-02-10 08:25

from django.db import migrations


def set_role_from_user_group(apps, schema_editor):
    LogReportRead = apps.get_model("incidents", "LogReportRead")

    for log in LogReportRead.objects.select_related("user"):
        if not log.user:
            continue

        groups = log.user.groups.all()

        if groups.exists():
            log.role = groups.first().name
        else:
            log.role = ""

        log.save(update_fields=["role"])


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0055_Populate_missing_entity_in_log"),
    ]

    operations = [
        migrations.RunPython(set_role_from_user_group),
    ]
