# Generated by Django 5.2.13 on 2026-04-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0057_alter_incident_incident_timezone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="incident_id",
            field=models.CharField(max_length=28, verbose_name="Incident Reference"),
        ),
    ]
