# Generated by Django 6.0.4 on 2026-04-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0058_alter_incident_incident_id"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="emailtranslation",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="impacttranslation",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="predefinedanswertranslation",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="questioncategorytranslation",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="questiontranslation",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="sectorregulationtranslation",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="sectorregulationworkflowemailtranslation",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="workflowtranslation",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="emailtranslation",
            constraint=models.UniqueConstraint(
                fields=("language_code", "master"),
                name="incidents_email_translation_uniq_lang",
            ),
        ),
        migrations.AddConstraint(
            model_name="impacttranslation",
            constraint=models.UniqueConstraint(
                fields=("language_code", "master"),
                name="incidents_impact_translation_uniq_lang",
            ),
        ),
        migrations.AddConstraint(
            model_name="predefinedanswertranslation",
            constraint=models.UniqueConstraint(
                fields=("language_code", "master"),
                name="incidents_predefinedanswer_translation_uniq_lang",
            ),
        ),
        migrations.AddConstraint(
            model_name="questioncategorytranslation",
            constraint=models.UniqueConstraint(
                fields=("language_code", "master"),
                name="incidents_questioncategory_translation_uniq_lang",
            ),
        ),
        migrations.AddConstraint(
            model_name="questiontranslation",
            constraint=models.UniqueConstraint(
                fields=("language_code", "master"),
                name="incidents_question_translation_uniq_lang",
            ),
        ),
        migrations.AddConstraint(
            model_name="sectorregulationtranslation",
            constraint=models.UniqueConstraint(
                fields=("language_code", "master"),
                name="incidents_sectorregulation_translation_uniq_lang",
            ),
        ),
        migrations.AddConstraint(
            model_name="sectorregulationworkflowemailtranslation",
            constraint=models.UniqueConstraint(
                fields=("language_code", "master"),
                name="incidents_sectorregulationworkflowemail_translation_uniq_lang",
            ),
        ),
        migrations.AddConstraint(
            model_name="workflowtranslation",
            constraint=models.UniqueConstraint(
                fields=("language_code", "master"),
                name="incidents_workflow_translation_uniq_lang",
            ),
        ),
    ]
