# Generated by Django 6.0.5 on 2026-05-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0059_alter_emailtranslation_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectorregulation',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
