name: Docker pre-build checks

on:
  workflow_dispatch:

env:
  TEST_IMAGE_FULLNAME: "nisinp:test"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: "<user>"
          POSTGRES_PASSWORD: "<password>"
          POSTGRES_DB: "serima-governance"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build for test
        uses: docker/build-push-action@v6
        with:
          file: docker/Dockerfile
          context: .
          load: true
          tags: ${{ env.TEST_IMAGE_FULLNAME }}
          build-args: |
            APP_VERSION=${{ github.ref_name }}

      - name: Test for any missing migration
        run: >
          docker run --rm --network=host -e DEBUG=false
          -v $PWD/governanceplatform/config_dev.py:/app/governanceplatform/config.py:ro
          --entrypoint bash
          ${{ env.TEST_IMAGE_FULLNAME }}
          -c '/app/manage.py makemigrations --check'

      - name: Run test application
        run: >
          docker run --rm --network=host -e DEBUG=false
          -v $PWD/governanceplatform/config_dev.py:/app/governanceplatform/config.py:ro
          --detach
          --name nisinp-test
          ${{ env.TEST_IMAGE_FULLNAME }}

      - name: Check healthz endpoint
        # exponential backoff so --retry 6 is about 60 seconds
        run: >
          curl --fail -H "Accept: application/json" -v --retry-connrefused --retry 6 http://127.0.0.1:8888/healthz;

      - name: Stop test application
        run: >
          docker stop nisinp-test || true
