# Generated by Django 4.2 on 2023-05-16 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Regulator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('regulator_identifier', models.CharField(max_length=64)),
                ('regulator_name', models.CharField(max_length=64)),
                ('regulator_country', models.CharField(max_length=64)),
                ('regulator_adress', models.CharField(max_length=255)),
                ('regulator_email', models.CharField(blank=True, max_length=100, null=True)),
                ('regulator_phone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('regulator_monarc_path', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RegulatorUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_phone_number', models.CharField(max_length=30)),
                ('regulator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regulator.regulator')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('sector_name', models.CharField(max_length=100)),
                ('sector_parent_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='regulator.sector')),
                ('sector_regulator_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='regulator.regulatoruser')),
            ],
        ),
    ]
